### ISSUE TITLE
可以开发一个可以在openwrt或LEDE上运行的zeronet吗？

### ISSUE THREAD

**Issue by tianlichunhong** [HelloZeroNet/ZeroNet#1106]
这样就一直在线，而且同步非常容易。手机版本的太耗流量。PC端的因为不能一直在线，每次同步时间都比较久。

**Comment by skwerlman** [comment]
OpenWRT can already run Python3 (https://wiki.openwrt.org/doc/software/python), so I don't think there's much keeping you from running zeronet on it.

The only downside would be that routers tend to have very small amounts of disk space, so you would need to find a way around that issue.

Caution: These instructions are a best-guess at the installation procedure. Only use them if you know what you're doing.
```
opkg install python3
pip3 install -U msgpack gevent
git clone https://github.com/HelloZeroNet/ZeroNet/
cd zeronet
python3 zeronet.py -h
```

**Comment by ky0ncheng** [comment]
Please ask in english and read manual first.

**Comment by skwerlman** [comment]
@ky0ncheng it's often better to have issues reported in the user's native language if they don't speak english, since it lets everyone else use more than one translation tool, or even knowledge of that language, to get an understanding of the problem. If the user submits a google- or bing-translated report, there's no opportunity to use other, potentially more accurate, translation methods, and it can often irreversibly mangle the content.

**Comment by katcom** [comment]
I did a translation.His request is that

Should a version of zeronet that can be ran on the openwrt and LEDE platform be developed?
This would allow zeronet being online at any time, and be easy with synchronizing data. The flow rate is fairy high while it runs on mobile phone. In case of running on PC, due to the fact that it could not continue being online, the interval between synchronizations will be pretty long.(I think he means the data would not be synchronized frequently while zeronet is ran on PC.)

**Comment by skwerlman** [comment]
His request was already answered by my first post, which points out that you can already install 0net on LEDE and OpenWRT.

**Comment by webserfer** [comment]
There is ready package and web-interface for OpenWRT?

**Comment by skwerlman** [comment]
@webserfer Unfortunately there is no zeronet package for openwrt; you'll need to install it manually. For a web interface, you can run it in proxy mode.

**Comment by rubo77** [comment]
dependencies are msgpack-python python-gevent

**Comment by tangdou1** [comment]
It can be closed.

**Comment by DaniellMesquita** [comment]
It could work on a router, but having the data folder on other device

**Comment by DaniellMesquita** [comment]
A good score to Dat, because sites can be in any folder
