### ISSUE TITLE
How to solve this problem?I had already open the port 15541.

### ISSUE THREAD

**Issue by JunerLee** [HelloZeroNet/ZeroNet#1159]
![_20171022132225](https://user-images.githubusercontent.com/16233029/31858525-53f38f3e-b72c-11e7-946f-6acbc7e18be8.png)

**Comment by krixano** [comment]
You can't publish because there are no peers to publish to. This is fine, you don't need to publish. The reason for this is because other people will just request the zite/content from your computer when they visit it. As long as your zite/content is signed, people will be able to fetch the files from your computer once they visit the zite.

**Comment by JunerLee** [comment]
@krixano You mean that I just let some friends to visit my zite and they will fetch files from my computer? More people visit is more easy to visit and publish? Am I right? (Forgive my f*cking poor English please ,hope that you can understand what I say.)

**Comment by krixano** [comment]
Yes, the *first* peer will fetch from your computer. From then on, once you make changes you will have to publish because then new people won't necessarily visit your computer, but could visit someone else's.

**Comment by JunerLee** [comment]
@krixano thanks,I can publish my zite now. :0
http://127.0.0.1:43110/1DNMzXs1BZ2PUZX19kbUkDjQ5sNcwnR1z6/

**Comment by skwerlman** [comment]
a good way to add peers to your zite is to visit it from a couple 0net proxies, which will download and share it for you

**Comment by grez911** [comment]
@JunerLee Please, close the issue if problem have been solved.

**Comment by JunerLee** [comment]
@grez911

**Comment by JunerLee** [comment]
ok ,sorry .
