### ISSUE TITLE
Semantic URLs

### ISSUE THREAD

**Issue by grez911** [HelloZeroNet/ZeroNet#1161]
There is no way I can have a [semantic URLs](https://en.wikipedia.org/wiki/Semantic_URL) in the current state of ZeroNet, am I right? Except of storing each post in a separate file, which is not feasible for dynamic sites.
I want links look like this http://127.0.0.1:43110/example.bit/post/121 instead of http://127.0.0.1:43110/example.bit/?Post:121
It will be good if it's possible to define a regex for requests which must be directed to index.html, where they will processed by JavaScript, instead of direct file access.

**Comment by krixano** [comment]
Currently, you can make it look like what you want, just with an added `?`, so: `http://127.0.0.1:43110/example.bit/?/post/121`. This is how my ZeroFrame Router works. I don't really see a problem with using this methods, and to me it's less complicated because everything is right there is javascript, no need to mess with regex's in the content.json file, etc.

**Comment by trenta3** [comment]
Please see issue #1548 and associated PR #1549

**Comment by imachug** [comment]
@HelloZeroNet @grez911 Can this issue be closed? We have #1548 now that basically replaces this issue.
