### ISSUE TITLE
A lot of "privacy projects" are liars (about ZeroNet's ignored worst security threat)

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#1180]
Since the middle of the year I'm talking to ZeroNet about the worst bug here, but I'm being ignored.
Is intentional of some open-source project's maintainers to left security issues?!
https://github.com/HelloZeroNet/ZeroNet/issues/1016

**Comment by imachug** [comment]
I understand this problem as well. On the other hand, I have no ideas how to solve this and don't break anything. Maybe you can try to fix this for yourself and then merge it to upstream?

**Comment by Plasmmer** [comment]
The best developers of ZeroNet can't do it because the owners of world are prohibiting it.
Also, ZeroNet and his security isn't for ME, but for ALL THE USERS, so why is just me to fix a error that isn't related just to me?

**Comment by imachug** [comment]
https://github.com/imachug/ZeroNet/commit/3ae2cd53986be2724a334754aa06f47cf7a5b2af

**Comment by imachug** [comment]
Right now I understand my problem. I lower by 10, right? Before I switched back to `master` branch, sites weren't loaded. So there are too many 404.

**Comment by HelloZeroNet** [comment]
Like I said in the linked issue: I have not found any suspicious activity and if it's really an attack then banning based on ip address is not a viable solution as anyone can generate unlimited ammount of .onion address.

**Comment by krixano** [comment]
@Plasmmer Firstly, you need to give substantial proof. You have not done so as far as I'm aware.
Secondly, if there is an issue, propose a way to fix it.
Thirdly, stop being a jerk. Things aren't going to get fixed with the type of tone you have when speaking to people. Especially since you tend to *overexagerate* a lot.
Next, don't jump to conclusions just being your "being ignored". This ties in with "stop being a jerk" from above. I'm talking about these clear assumptions: "because the owners of the world are prohibiting it" and "Is intentional of some open-source project's maintainers to left security issues?!". 

No wonder your being ignored (if you actually are being ignored). No one wants to talk to someone who is overly suspicious *with nothing to back up their claims* who tends to overexagerate and is a jerk when talking to people.

**Comment by imachug** [comment]
@krixano Strange, but I have something to argue now. I can't give you an example, but it the problem exists. I often create a site, then publish it to proxy and give a link to somebody. You know what's happening? After I publish, nothing changes: neither on proxy, neither on new peer's computer. That doesn't happen for ALL sites, but it does happen for SOME sites.

Though I agree that @Plasmmer should at least propose a *working* way to fix it. I've tried to add what he wanted (I even didn't lower by 20, I changed by 10), but from there I didn't receive any updates - there are too many errors peers send, so my change just blocked everybody.

**Comment by krixano** [comment]
@imachug I've only ever had that problem when the file being transferred was big (1MB or more). And that is just because it needs to download the file before it can use it. After waiting till it's downloaded, then it updates. I had this problem with ZeroMedium because the whole zite is over 1MB.

**Comment by HelloZeroNet** [comment]
@imachug I can hardly imagine that your problem was caused by an attack on the network. 

There was an error in the rate limiting algorithm that could have caused problem like you described. I fixed some days ago in Rev3137: https://github.com/HelloZeroNet/ZeroNet/commit/5026f1b0a8bad418fcc9baf0137e5f7ee877513c

Please open an issue if you still experiencing it after the update.

**Comment by imachug** [comment]
@HelloZeroNet That was quite long ago, so I think you've already fixed this.

**Comment by aero31aero** [comment]
Also, this might be relevant here: https://www.reddit.com/r/programminghorror/comments/7cmajw/newbie_reported_network_issue_as_the_worst/

Do community guidelines prohibit such issues from being left unedited by the moderators?
