### ISSUE TITLE
Automate Testing

### ISSUE THREAD

**Issue by shakna-israel** [HelloZeroNet/ZeroNet#122]
Could I suggest integrating something like [Travis-CI](http://docs.travis-ci.com/user/languages/python/) into the flow of things?

Things like testing to see if PEP8 is passing, and all the written tests still pass automatically takes a lot of effort out of reviewing any pull requests

**Comment by HelloZeroNet** [comment]
It would be nice, but before that we need better tests. i'm not really experienced in that, but i try to do my best :)

**Comment by shakna-israel** [comment]
I could have a go at putting together some unittests, if you're interested. Not the best at it, but I'm learning.

**Comment by shakna-israel** [comment]
I've renewed my fork, and attempted to start adding some automated testing to it.

Health-wise, Landscape says ZeroNet is at about [70%](https://landscape.io/github/shakna-israel/ZeroNet/2/messages), which isn't too bad. There's just a lot of semantic things, to do with the various PEPs.

**Comment by HelloZeroNet** [comment]
Thanks! We [started to make it](https://github.com/HelloZeroNet/ZeroNet/pull/119) PEP8 compatible, not every file converted yet.
Some of the test are broken yet because I only recently started to the [files](https://github.com/HelloZeroNet/ZeroNet/tree/master/src/Test/testdata) that required for it.

**Comment by border0464111** [comment]
Travis seem to be implemented by now closing ?
