### ISSUE TITLE
GET request show that port = 0 and Tracker response that invalid port.

### ISSUE THREAD

**Issue by TaibiaoGuo** [HelloZeroNet/ZeroNet#1248]
I try to build a tracker in the Internet and I have Public IP. But I can not communicate correctly with my HTTP tracker because ZeroNet always send request that port = 0.
I use wireshark to catch the bag and found that as following:
```
GET /announce?uploaded=0&downloaded=0&numwant=30&compact=1&event=started&peer_id=-ZN0060-Dsh93Nert4Sr&port=0&info_hash=%E7H.%B4%9D%8B%A7%08%DA%C7%90%0F%B0%AA%EAW%81%95%2C%F3&left=0 HTTP/1.1
Host: 18.217.*2.***:7777
User-Agent: Python-urllib/2.7
Accept-Encoding: identity
X-Lantern-Version: 4.4.1

HTTP/1.1 200 OK
Date: Wed, 17 Jan 2018 05:07:33 GMT
Conne4ction: keep-alive
Content-Length: 34

d14:failure reason12:invalid porte
```

But this problem didn't show when I connect the trackers which ZeroNet build-in.

And I'm sure that when I send the right request as following:
```
import urllib2
#import time
url = "http://18.217.9*.***:7777/announce?uploaded=0&downloaded=0&numwant=30&compact=1&event=started&peer_id=-ZN0060-aQg0kBTLErmd&port=15441&info_hash=%1D%AF%97%C8%1F%99%C3%83%90%86%29%2BhZB7%A9%A4%DD%D2&left=0"
req = urllib2.urlopen(url,timeout = 25)
response = req.read()
print response
req.fo.sock.recv = None
req.colse()
req.None
```
The return is right as following:
```
d8:completei1e10:incompletei0e8:intervali600e5:peers6:?:<Q6:peers60:e
```

**Comment by HelloZeroNet** [comment]
Thanks for the detailed report. 
We send port = 0 when the client is in passive mode (without public ip) to avoid listing it to other clients. Looks like it's not compatible with every tracker software. I have just tested your code with the trackers we currently using and all accepts port=0. 
To avoid this problem we have to find an other way to get the peer list without putting my ip to the list.

**Comment by HelloZeroNet** [comment]
I have added a future support of reporting port=1 instead of 0 in the future for peers that does not have opened port: https://github.com/HelloZeroNet/ZeroNet/commit/2575476086ef088a010e10433146c0d05db3adec

It's still reports port 0 at the moment to avoid compatibility issue with clients that has not updated yet, this change will allow us to change it in the future.

I also changed the left bytes from 0 to 431102370 (fake amount), because some trackers does not worked well with 0 value https://github.com/HelloZeroNet/ZeroNet/commit/3e51b888cb9523f6060419259fa7d29a86e88d13

**Comment by imachug** [comment]
@HelloZeroNet Looks like this issue was resolved?
