### ISSUE TITLE
Code changes allow you to bypass restrictions

### ISSUE THREAD

**Issue by DATSEC** [HelloZeroNet/ZeroNet#1397]
![imgу](https://i.imgur.com/DgPhNbZ.jpg)
We added a torrent link to your zeroUP
you know the rules such a file size is not allowed and the more so the format of the torrent

**Comment by krixano** [comment]
Well, the "restrictions" (which are more like checks) that are built in the code are obviously going to be able to be bypassed by changing the code on the user's side. However, you cannot change which files are seeded to other people because that is set only by the owner of the site using their signature in the `content.json` file at the root of the data/users directory.

**Comment by DATSEC** [comment]
@imachug You can go to ZeroUP and see this torrent in your network.
Also I can upload any other file with any extension.

**Comment by krixano** [comment]
It depends on if ZeroUp has anything for the "allowed_optional_files" option in the content.json file I mentioned before. If it does and the file extention you've uploaded isn't in there, then the files are *not* seeded to anybody else as far as I'm aware.

**Comment by imachug** [comment]
@krixano

> Although, not sure if big files are included in that.

They are included.

> it is probably being added to the database

Good point, I haven't thought about this!

**Comment by imachug** [comment]
@HelloZeroNet Close because of inactivity?
