### ISSUE TITLE
Coffeescript compiling problems in linux

### ISSUE THREAD

**Issue by canterburycomputers** [HelloZeroNet/ZeroNet#141]
Hi,

There seems to be an error when running in debug mode on linux.  When running zeronet with 

    python zeronet.py --debug --coffeescript_compiler "/usr/local/bin/coffee"

i get the following error when browsing to one of my sites (not yet compliled)

    command = config.coffeescript_compiler % os.path.join(*file_path.split("/"))  # Fix os path separator
    TypeError: not all arguments converted during string formatting

I have managed to fix this on my machine by changing line 59 of src/Debug/DebugMedia.py from:

    command = config.coffeescript_compiler % os.path.join(*file_path.split("/"))  # Fix os path separator

to:

    command = config.coffeescript_compiler + ' ' + os.path.join(*file_path.split("/")) # Fix os path separator

I'm not sure if this is the correct way to fix this but it seems to work fine in windows too.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, its fixed in latest version https://github.com/HelloZeroNet/ZeroNet/commit/dd2bb8b3fbd5d6eb6d950cdb48f2e3691a393e2d: 
Starting with `python zeronet.py --debug --coffeescript_compiler "/usr/local/bin/coffee -p"`, and autodetection of coffee command also added, so simply `python zeronet.py --debug` should work now
