### ISSUE TITLE
Errors when I load a site offline

### ISSUE THREAD

**Issue by byaeger** [HelloZeroNet/ZeroNet#1414]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Microsoft Windows 7
  * Web browser: Google CHrome
  * Tor status: available
  * Opened port: no
  * Special configuration: None

### Step 2: Describe the problem:

When I try to load a site while i'm offline, all I get is errors.

#### Expected Results:

I expected it to load any way as it is peer-to-peer.

**Comment by imachug** [comment]
What errors do you get and where do you get them?

**Comment by byaeger** [comment]
While I am offline, I load a site from ZeroSites, then it says connecting announcing 0 errors 8
![screen](https://user-images.githubusercontent.com/33613777/39670406-0cb51724-50b9-11e8-8c5b-9bab7b2ef296.PNG)
.

**Comment by imachug** [comment]
Oh, that's normal. When you have no internet connection, it can't connect anywhere - including other peers. You must have your connection on for ZeroNet to work. ZeroNet won't access any Internet sites except trackers. The error is shown because it can't connect to trackers (because Internet is offline).

Probably what you are looking for is called meshnet. In meshnet routers communicate without internet connection. (though the network wire must be plugged in)

**Comment by Thunder33345** [comment]
i thought zeronet is perfectly capable of loading the site via an offline last know well archive?
if it has been peered/downloaded?

**Comment by imachug** [comment]
If it was loaded before, ZeroNet can open it.
