### ISSUE TITLE
Is ZeroBoard a real decentralized zite ? 

### ISSUE THREAD

**Issue by kzoacn** [HelloZeroNet/ZeroNet#1416]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Windows 10
  * Web browser: Chrome
  * Tor status: disabled
  * Opened port: no
  * Special configuration: None

### Step 2: Describe the problem:

I notice that there are some code at /data/1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp/js/all.js line 591
`
        return $.post("https://zeroid.qc.to/ZeroBoard/add.php", {
          "body": body,
          "auth_key": auth_key,
          "hash": hash
        }).always(this.submittedMessage);
`
So we need a robot in https://zeroid.qc.to to make sure ZeroBoard works.

#### Expected Results:

How can we build a real dynamic and decentralized zite ?

**Comment by imachug** [comment]
**ZeroBoard is outdated.** It is unsecure and uses clearnet. It is possible to make a board without clearnet, and probably @HelloZeroNet doesn't have much time to do it. But I think we should at least add a warning.

By the way, you should have posted this issue here: http://github.com/HelloZeroNet/ZeroBoard

**Comment by kzoacn** [comment]
Thanks !
