### ISSUE TITLE
nginx reverse proxy : Forbidden Invalid host

### ISSUE THREAD

**Issue by ky0ncheng** [HelloZeroNet/ZeroNet#1420]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: ubuntu 16.04.2
  * Web browser: chrome
  * Tor status: not available/always/disabled
  * Opened port: yes
  * Special configuration: ____

https is work, but page display Forbidden Invalid host

**Comment by ky0ncheng** [comment]
How to use zeronet bundle without nginx to host https?

**Comment by grez911** [comment]
Why do you duplicate similar issues? Please, close this because it will just make people angry and definitely not help to solve your problem more quickly.

> How to use zeronet bundle without nginx to host https?
It's currently not possible and I personally against implementing this into ZeroNet core, because this is what mature projects exists for, such as nginx -- for handling multiple connections and providing SSL encryption via https protocol.
