### ISSUE TITLE
Questions ZeroNet

### ISSUE THREAD

**Issue by Shydoo** [HelloZeroNet/ZeroNet#1449]
Hello, 

I would like to create a marketplace platform like Openbazaar.org so I have a lot of questions. :)

1 - Why hasn't OpenBazaar installed on Zeronet?
2 - In the same example (Creating a market), is it necessary to implement the ZeroID authentication system to make market user accounts work or is there another equivalent solution?
3 - A site system with a user account with a private message, the publication of a message on a forum or to write a product notice, the publication of an image on the forum or for the image of a product sold, the publication of an article by users, the management of their stock, the creation and customization of their shop as part of a marketplace on ZERONET?
4 - Should I use ZeroID to implement features like these before?
5 - What ZeroID equivalent is used to create similar features?
6 - Possibility of status data for some members as "Moderator" or "Administrator" as well as features such as banning members, closing some stores that will not comply with laws, deleting an item without closing the shop entirely, the alert system? With ZeroID or equivalent? Why? Why? Why? Why?
7 - To have the possibility of implanting other cryptomonnaie than the Bitcoin to leave to the sellers and buyers a broad choice of type of payment?
8 - Possibility of setting up a so-called "Escrow*" system? Is there a function to deposit his money on the portfolio on the site or on the contrary, if the customer can use his own portfolio synchronized possibly to his ZeroID account?
9 - For the creator of the site is it possible that it is a panel with modifiable parameters like the percentage of commission, to be able to add or remove categories of products, to put a filtering system to avoid putting an article online if there are certain non-compliant words?
10 - Is a market technically stable and feasible? If so, how to create a market? What are the tools, modules or functions to use to create a market site on ZERONET (ZeroID? ...)?
11 - How does an escrow system work?
12 - How to implement it in a zite?

ZeroNet Security... :
13 - Is it possible that a zite is closed by the government?
14 - It seems to me that the Chinese firewall had blocked the p2p client's communication port, but according to the new ZeroNet update, the port changes randomly (one of the solutions was to use a fixed port (15441) that the client listens to on a random port (10000-4000000)), but does this risk still have value?
15 - Can a user account be hacked? Knowing that he uses cryptography similar to Bitcoin.
16 - Are there large security holes that could occur on a Zeronet site (roughly if user accounts could be hacked, if spying is possible and data recovery, if one or more people could close the site) despite the p2p system.
17 - Is there an interest in making zite updates? Because it's very secure with block string and file cryptography.
18 - What happens when someone hosts malicious content?
19 - Advantages and disadvantages of ZeroNet?
Thank you very much if you could answer me. ;-)
See you soon !

Regards,
Shydoo

**Comment by anoadragon453** [comment]
> Why hasn't OpenBazaar installed on Zeronet?

Up to them, IPFS is more well-known (for now ;)

>  In the same example (Creating a market), is it necessary to implement the ZeroID authentication system to make market user accounts work or is there another equivalent solution?

It's not necessary, but it's the easiest to do IMO. If you want to support alternative methods for authentication it may be possible, but it depends what those methods are.

> A site system with a user account with a private message, the publication of a message on a forum or to write a product notice, the publication of an image on the forum or for the image of a product sold, the publication of an article by users, the management of their stock, the creation and customization of their shop as part of a marketplace on ZERONET?

Not really sure what the question is here, but yes those features can all be done on ZeroNet.

> Should I use ZeroID to implement features like these before?

You can use any ID provider, but ZeroID is the best supported. There is talk of a new provider, KxoID, coming out in the next few weeks, so keep your eyes open.

> What ZeroID equivalent is used to create similar features?

Maybe you mean [ZeroFrame](https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/)? ZeroID is just for authentication.

>  Possibility of status data for some members as "Moderator" or "Administrator" as well as features such as banning members, closing some stores that will not comply with laws, deleting an item without closing the shop entirely, the alert system? With ZeroID or equivalent? Why? Why? Why? Why?

Yes you can have certain users moderate your content. This should probably be fleshed out a little more though, giving users the ability to only moderate certain files (`data/users/*` and not `content.json` and the like.) Is this already possible @HelloZeroNet?

> To have the possibility of implanting other cryptomonnaie than the Bitcoin to leave to the sellers and buyers a broad choice of type of payment?

Sure, OpenBazaar does this through centralized service, ShapeShift.io. If there were a decentralized exchange, then one could theoretically use any cryptocurrency. I know some exist, but none on ZeroNet at the moment.

We're really not limited to Bitcoin though.

> Possibility of setting up a so-called "Escrow*" system? Is there a function to deposit his money on the portfolio on the site or on the contrary, if the customer can use his own portfolio synchronized possibly to his ZeroID account?

OpenBazaar does escrow through individuals whom the buyer and seller agree on using. ZeroNet could do the same thing. We really need a bitcoin/electrum plugin @imachug :)

> For the creator of the site is it possible that it is a panel with modifiable parameters like the percentage of commission, to be able to add or remove categories of products, to put a filtering system to avoid putting an article online if there are certain non-compliant words?

Sure, you can do whatever you like with your interface, it's just a website. You could do filtering of words as well, but it would have to not only be done when a user publishes a page, but also when another user loads a page, otherwise one could just go into the site files and change it there.

> Is a market technically stable and feasible? If so, how to create a market? What are the tools, modules or functions to use to create a market site on ZERONET (ZeroID? ...)?

Take a look at the [ZeroNet documentation](https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/), the [ZeroNet dev resource](http://127.0.0.1:43110/138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/?Page:devresources), the [ZeroNet dev center](http://127.0.0.1:43110/14pM9huTYzJdyQyHRj6v2kfhMe8DrxwpGt/?/tutorials) and [The Truth About ZeroNet](https://github.com/krixano/ZeroNet-Dev-Center/issues/28) for good documentation on ZeroNet development.

> How does an escrow system work?

https://openbazaar.zendesk.com/hc/en-us/articles/207548366-What-are-moderated-payments-

> How to implement it in a zite?

Have a buyer send their payment to another user (escrow). Seller sends the product. Buyer tells escrow that everything's good and escrow gives payment to Seller OR Buyer says they did not receive product and gets their money back.

> Is it possible that a zite is closed by the government?

Not really. That's the whole point of ZeroNet :P 

>  It seems to me that the Chinese firewall had blocked the p2p client's communication port, but according to the new ZeroNet update, the port changes randomly (one of the solutions was to use a fixed port (15441) that the client listens to on a random port (10000-4000000)), but does this risk still have value?

10000-40000* yes. This stops the Chinese government from doing basic traffic blocking, but if they started doing deep packet inspection then we'd need to change things. ZeroNet can use Tor with Meek proxies, but I don't know if those don't work anymore since Amazon/Google stopped hosting theirs @HelloZeroNet ?

> Can a user account be hacked? Knowing that he uses cryptography similar to Bitcoin.

Not unless their private key is shared somehow. Don't post it on any websites or give it out to anybody willingly and you'll be fine :) Nobody can randomly guess a private key like they can for a password.

> Are there large security holes that could occur on a Zeronet site (roughly if user accounts could be hacked, if spying is possible and data recovery, if one or more people could close the site) despite the p2p system.

You'll never write software that's free of bugs or vulnerabilities. OpenBazaar v1 had some bad vulnerabilities iirc. Stick to the latest versions of your software and you'll likely be pretty well off.

> Is there an interest in making zite updates? Because it's very secure with block string and file cryptography.

Not sure what you mean. The creator of a zite or anyone they've deemed trustworthy can update their zite.

> What happens when someone hosts malicious content?

Up to the zite owner to take it down, or for people to block/blacklist that content.

> Advantages and disadvantages of ZeroNet?

Over OpenBazaar? Can be hosted on a public proxy I guess. Can do much more than just a marketplace. It's a general protocol, so you can do many things with it.

Hope that at least somewhat helps. I suggest you read up a bit on the links I provided above so you can get a good grasp of what ZeroNet is and what it can do.

Thanks for asking!

**Comment by Shydoo** [comment]
Thank you very much ! :wink: 

I have got another questions :smiley: : 

1- How to be as anonymous as possible? Should I2p be used?
2- Can I really use I2P with Zeronet?
3- I2P encrypts communications?
4- Does PGP encrypt communications?
5- ZeroID contains a short centralized server it is all except in the line of decentralization?
6- What is zeroframe? What's the point?
6.1- Can user names be created directly on the site using zeroframe?
7- What is clearweb and clearnet?
8- Whether it is ZeroID PolarID PeakID KaffieID I imagine it all works the same way as ZeroID with a centralized server that will do data checks on the clearweb?
9- How to make the site as anonymous, secure and encrypted as possible? What should be used (currently functional)? Whether it's for the id?  For network overlay (Tor, I2P)?
10- Let's imagine users who protect themselves as much as possible, doing manipulation on the site side, we can make it really safe ?

Thank you in advance ! :smile:

**Comment by Thunder33345** [comment]
>2- Can I really use I2P with Zeronet?

As far as i know, we cant for now
>5- ZeroID contains a short centralized server it is all except in the line of decentralization?

Yes but we have other ids that dont have central point of failure like kaffie ID, which allows anyone to have the same name and so on
>6- What is zeroframe? What's the point?

Zeroframe is the API library for connecting between site's script to the zeronet instance
>6.1- Can user names be created directly on the site using zeroframe?

Yes to some extend, you still need the site's signing cert/signed cert to use it
the zeroframe API allows you to do a lot of things, like prompting user etc

>7- What is clearweb and clearnet?
AFAIK both are same, we annotate "clearnet" when a link is links to the clearnet aka this network we are now using which allows sites to get your IP etc and may pose a danger to your privacy

>8- Whether it is ZeroID PolarID PeakID KaffieID I imagine it all works the same way as ZeroID with a centralized server that will do data checks on the clearweb?
no, some are actually decentralized, allowing anyone to sign any names thus there's always duplicates in ID names
some depend on clearnet to check/verify uniqueness of an account name, or to link accounts etc

ZeroID is the one mainly used, it uses clearnet to check for uniqueness and is vulnerable to single point of failure, scale: no registering if auth server down

KaffieID is the other one that's sometimes used, it dosent have a clearnet access it also is decentralized and allows same usernames due to no one will be verifying/checking/forcing usernames

PolarID and PeakID both uses clearnet as far as i known, they also need a google account for linking popurses to verify an account "uniqueness" as in preventing user to make tons of account, one of them enforce unique nickname one dosent and both uses a server to verify info

Dont quote me on that one since these two are the one i am less familiar with
there's also a lot more id providers less mentioned

>9- How to make the site as anonymous, secure and encrypted as possible? What should be used (currently functional)? Whether it's for the id? For network overlay (Tor, I2P)?

use tor AND tor browser

>10- Let's imagine users who protect themselves as much as possible, doing manipulation on the site side, we can make it really safe ?

dont understand what you meant

**Comment by DaniellMesquita** [comment]
@anoadragon453

**Comment by imachug** [comment]
@HelloZeroNet I think most (if not all) questions were answered, could you close this please?
