### ISSUE TITLE
Configuration page [In progress]

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1478]
# Why?

To allow easily change basic settings of ZeroNet: Add/change trackers, disable browser start with ZeroNet, etc.

# Plan
- [x] Static design of config page
- [x] API command to list current/default settings
- [x] Dynamic config page
- [x] Save values
- [x] Support client restart with API call
- [x] Offer restart client if necessary
- [x] Add settings to loading site page (to allow change settings in case of failed load of ZeroHello)
- [x] Start_browser setting should respect config value over argument
- [x] Test trackers / trackers files settings to work without restart of zeronet client
- [x] Properly save multiline configuration values
- [x] Properly handle delete multiline configuration values

**Comment by tangdou1** [comment]
I am a passive node, but I can still connect others even if all trackers are banned, because I save the active nodes IP and Port in my local database. 
Now is it easy and possible to combine the function that people can easily add the active nodes information into their own database if all the trackers are baned and the meek-tor is also baned into the Configuration page?
