### ISSUE TITLE
IDEA: ZeroPaste

### ISSUE THREAD

**Issue by bashrc** [HelloZeroNet/ZeroNet#158]
A pastebin-like system in which posts expire after some (perhaps selectable) amount of time.

**Comment by sbDevGit** [comment]
+1

**Comment by naab** [comment]
The technical issue with the "expires after some amount of time", is that a User able to delete the pad (the guy who created it, or maybe a set of persones) NEEDS to access the website some way, in order to publish the deletion to the network. Unless you authorize more people moderate (ie: able to delete files automatically), but you have to trust these guys. Or code a bot with admin rights doing the job.

To resume, it's not that easy to have auto-deletion in a p2p system.

**Comment by ThomasdenH** [comment]
Can't the original user give the content an expiration date after which users won't share the content anymore?

**Comment by naab** [comment]
We don't have this kind of control on file sharing yet. Opening a ticket.

**Comment by naab** [comment]
No you can't. And also, i'm not sure a TSLV (time since last visited/downloaded) is the solution. For this to work, all users have to archive all the pages accessed + the timestamp. It is a faily huge amount of data you can't delete that easily. 

The solution may be an implementation that downloads only requested sites :

=> https://github.com/HelloZeroNet/ZeroNet/issues/144

If this solution is implemented, the p2p paradigm will naturally delete non-accessed files. And if a user owning the pad visits it after the expiration date, he can send the deletion to peers.

You can imagine a system mixing both (actual implementation + the proposal above) : to download all defined files always, and be able to specify a "TTL" for specific files, where after some time, they move to the "download on visit only" mode.

**Comment by deavmi** [comment]
Who said pastses had to expire? :)

**Comment by TheNain38** [comment]
It could be something like [cryptobin](https://cryptobin.org), it could encrypt the paste, and users should know the password to decrypt it... And the user could delete a paste he created, as it will be signed by him.

**Comment by imachug** [comment]
For those who are still searching for ZeroPaste: [NullPaste](http://127.0.0.1:43110/1MgHVPCE1ve6QfKrgsqCURzRj72HrRWioz/). And my alternative to JSFiddle/CodePen: [CodeR](http://127.0.0.1:43110/1CodEr7T9xNXSPcwbsvf5fHTqsixDMwDzL/)

**Comment by imachug** [comment]
@HelloZeroNet Can we close this?

**Comment by imachug** [comment]
@HelloZeroNet Thanks!
