### ISSUE TITLE
[Enhancement] Use pip.

### ISSUE THREAD

**Issue by BenMcLean** [HelloZeroNet/ZeroNet#1584]
Basically, what the crap is this. https://github.com/HelloZeroNet/ZeroNet/tree/master/src/lib

ZeroNet is not a special snowflake. It needs to use pip like everybody else.

**Comment by BenMcLean** [comment]
Wow, that is a bigger project than I had anticipated. Is there a roadmap on that?

**Comment by HelloZeroNet** [comment]
No roadmap yet, it's planned around end of this year.

**Comment by satoshisfriendz** [comment]
PIP IS KING

**Comment by satoshisfriendz** [comment]
https://www.youtube.com/watch?v=XNtTEibFvlQ
2X playback

**Comment by satoshisfriendz** [comment]
How easy to use PIP installs.

**Comment by krixano** [comment]
Maybe a lot of OOP programmers don't think so, but just as a sidenote - a *lot* of people think pip and npm are actually really bad for several reasons.

**Comment by BenMcLean** [comment]
> Maybe a lot of programmers (most of them seem to be OOP or newer programmers) don't think so, but just as a sidenote - a lot of people think pip and npm are actually really bad for several reasons.

Those people would be obviously wrong for several really blatantly obvious reasons.

First, maintainability requires that we know exactly what version of all the dependencies we're building against so we know what changed when something breaks. Correct package management guarantees this. Embedding copies of the libraries with God-only-know what modifications means that when it comes time to update any of the dependencies, no one will know how -- not even the original programmers.

Second, modularity. The OOP programmers are correct about this.

Third, security. No one has time to audit the code in the embedded versions of the libraries in every repo of every project. You should be able to audit each dependency once by auditing that dependency's repo and thus guarantee that the code you audited is the code you're building and running against.

Fourth, leaving out package management has no benefits. There's no upside to not doing it. If the packaging system is ever retired, you can always paste the libraries back in.

**Comment by krixano** [comment]
> maintainability requires that we know exactly what version of all the dependencies we're building against so we know what changed when something breaks. 

And apparently a package management is required for this? And who says embedded libraries are modified directly?

> Second, modularity.

If we are saying package management is good because of modularity, we also need to know why modularity is good.

> Third, security.

This is one of the only good reasons for using a terrible package management system.

> Fourth, leaving out package management has no benefits. 

Actually it does, and they're "obvious".

>Now, if these people's problem was with the specifics of a particular package management system 

The problem is not package management in general. The problem is terrible package managers. The **other, more important** problem is that the whole system relies on centralization. If the server is down, nobody can install the packages required  for a project. 

Remember LeftPad?

**Comment by BenMcLean** [comment]
> If we are saying package management is good because of modularity, we also need to know why modularity is good.

I think that is obvious given the definition of modularity. Google it. Software modularity being a good (not necessarily the only good or the ultimate good, but being a good) is not a controversial proposition in computer science.

> The problem is not package management in general. The problem is terrible package managers.

Oh, OK that's reasonable.

> The other, more important problem is that the whole system relies on centralization. If the server is down, nobody can install the packages required for a project.

You're saying that on Github.

**Comment by krixano** [comment]
It is controversial that it's taken *way* too far. People "modularize" practicaly everything now without even thinking on whether it has any real benefit. There's also the fact that function calls and classes and modules and all of this stuff has a cost. Of course, you'll probably counter that computers are fast enough now. Then I'll counter with Windows 10 on HDDs, Browsers and practically every website out there, and npm.

I'm also going to add that there are languages that allow modifying libraries without modifying the code of the library directly. Called extensions or something like that. There's also metaprogramming.

**Comment by HelloZeroNet** [comment]
I removed most of the packages from the source code, but I had to keep pybitcointools, because the two pip package (python-bitcoinlib is the other) installs to the same bitcoin named directory in site-packages. So it's not possible to install both of them at the same time. I was surprised that pypi does not enforce to install to the same directory as the package name.
I also thinking about including pyelliptic as versions later than 1.5.6 does not have ECIES functions added.

**Comment by BenMcLean** [comment]
Nice! :)

**Comment by krixano** [comment]
@BenMcLean I don't know what programmers you follow, but maybe you should look at opposing views more often considering you seem to think that's everything is so obvious and believes the same things. Try Casey Muratori, Jonathan Blow, Abner Coimbre, and the like.

**Comment by krixano** [comment]
This has **nothing** to do with authority. It has everything to do with the fact that you think:
1.) "obvious given the definition of modularity"
2.) "is not a controversial proposition in computer science."
3.) "leaving out package management has no benefits"
4.) "It needs to use pip like everybody else"

Every single one of these is an *appeal to authority or majority*, and every single one of these is false - Why? Because the programmers that **actually care about programming and performance and the Users** know that things are more complex than you make them out to be. I'm talking about programmers that follow in the footsteps of Jonathan Blow, Abner, Casey - Game Programmers, Systems Programmers, etc.

The names I have given above are not **authority**. They are an example of how wrong you are that everyone knows this is like this, etc., etc.

**Comment by krixano** [comment]
Additionally, I've already evaluated your reasons and gave counters to almost all of them. You know this, and I think it's likely you know my counters are valid considering you didn't respond to them.

**Comment by BenMcLean** [comment]
> This has nothing to do with authority.

Your name-dropping of Casey Muratori, Jonathan Blow and Abner Coimbre was a textbook appeal to authority.

What I said about modulairty is Computer Science 101. Google it.

> "I'm talking about programmers that follow in the footsteps of Jonathan Blow, Abner, Casey - Game Programmers, Systems Programmers, etc. The names I have given above are not authority."

They're names. That makes them authority.

By "everybody else" I obviously meant other Python software packages, not literally every programmer on earth.

**Comment by krixano** [comment]
> Your name-dropping of Casey Muratori, Jonathan Blow and Abner Coimbre was a textbook appeal to authority.

No, it wasn't.

> They're names. That makes them authority.

No, it doesn't. I'll "drop" my name: Christian Seibold is another example of how obviously wrong you are. I'm certainly no "authority", Right? Therefore, you statement that name dropping makes those names an appeal to authority false.

Additionally, look at what I **said**:

> **follow in the footsteps** of ....
> They are an example
> Try ... **and the like**

**Comment by BenMcLean** [comment]
It's never an appeal to authority when you're doing it.

**Comment by krixano** [comment]
> They're names. You're citing them as justification

I did no such think. I cite them as **examples** which I have clearly said *multiple times*. If you are going to argue, have the decency to not deliberately forget about or chop off part of someone's argument:
> maybe you should look at opposing views more often considering you seem to think that everything is so obvious and everyone believes the same things

What do I say in this quote? Tell me!

**Comment by krixano** [comment]
Also, you being quite illogical here. You say name dropping means it's an appeal to authority. Yet if I drop names of friends I know that disagree with you, all of which are not popular or known by many people, would you say that's an appeal to authority? Clearly an appeal to authority has to appeal to **authority**, right?

**Comment by BenMcLean** [comment]
Examples are a form of justification.

> What do I say in this quote? Tell me!

A strawman fallacy that I'm ignoring.

**Comment by krixano** [comment]
You don't know what strawman fallacy is, do you?

**Comment by skwerlman** [comment]
this ticket is _wildly_ off topic and should either be closed or limited

**Comment by BenMcLean** [comment]
Oh, right. I didn't treat that as an attempt to refute what I said, but just as a comment, since it doesn't refute what I said.

> It is controversial that it's taken way too far.

Anything can be taken way too far, sure.

> There's also the fact that function calls and classes and modules and all of this stuff has a cost.

You want to go back to doing perfect Assembly for everything? If so, why are you commenting on an issue in a Python repo? This is Python. That ship has sailed.

If not, then where do you draw the line?

> I'm also going to add that there are languages that allow modifying libraries without modifying the code of the library directly. Called extensions or something like that. There's also metaprogramming.

Package management doesn't interfere with any of that AFAIK.

**Comment by krixano** [comment]
Let me summarize everything I've said thus far:

1.) **It is controversial** that it's taken way too far.
2.) maybe you should look at opposing views more often **considering you seem to think that everything is so obvious and everyone believes the same things.**
3.) know that **things are more complex than you make them out to be.**
4.) They are an example of **how wrong you are about things being so "obvious"** that everyone knows this is like that

My whole argument is refuting the fact that you think things are so "obvious".


> Package management doesn't interfere with any of that AFAIK.

I don't understand how you don't know that what you quoted was in response to saying that you don't **have** to modify code directly to change that code. Which means that there is a way to modify code without package management.

**Comment by BenMcLean** [comment]
> Examples are not a form of justification. They are evidence

Evidence is a form of justification.

> to refute the point that something "is not a controversial proposition in computer science".

It isn't. I know Jonathan Blow for certain does not hold that modularity is bad. It's been a foundational concept of programming since at least the 1960s.

> Notice that I haven't once explicitly said that these people are right.

Oh, it sure seemed that you were.

You seem to have taken my use of "everybody else" in a much stricter sense than I meant.

**Comment by BenMcLean** [comment]
I am gonna close this issue because my suggestion's already been implemented in the python 3 version.

**Comment by krixano** [comment]
>I know Jonathan Blow for certain does not hold that modularity is universally bad. It's been a foundational concept of programming since at least the 1960s.

This is an **actual** strawman fallacy. Let me point you to this!:
> The problem is not package management in general. The problem is terrible package managers. The other, more important problem is that the whole system relies on centralization. If the server is down, nobody can install the packages required for a project.

**Comment by krixano** [comment]
And the whole reason why I started this argument in the first place is because of this:
> If you can make a python program that uses libraries and is very easy to install without pip - then it obviously doesn't "need" pip. Stop imposing stupid Coding Practices on other people when they don't provide any actual benefit.

Let me further clarify - Don't act like a fucking asshole to someone just because their project doesn't use the tools **you** want them to use (and yes, I'm talking about your "snowflake" and "what the crap is this" comments).

**Comment by BenMcLean** [comment]
Every Python package with dependencies needs pip or something like it for the four reasons previously stated, none of which have been refuted.

It would be nice to look into decentralized alternatives to pip, but not into getting rid of package management altogether because that's stupid.

**Comment by krixano** [comment]
Why should a program that doesn't need security be forced to use pip when including the code directly can make it easier to install and ensure that the correct proper versions of the library are used and that they stay with the repo in case the library is no longer available.

Btw, I can see through your sudden change in your argument. lol

**Comment by BenMcLean** [comment]
I forgot one earlier.

Keeping the Git history clear of unnecessary deltas is a good enough reason all by itself even if there were no other.

**Comment by krixano** [comment]
And other people would say that a "clear history" provides no benefit and trying to do something like that is actually a downside because you are putting more importance on keeping things pretty and clean than functionality. Putting libraries in repos is a good way to ensure that if there's no other way to get the libraries, as long as your own source code is up somewhere, people have everything they need. They don't have to search (and potentially fail) to find the required libraries.

**Comment by BenMcLean** [comment]
If that happens, you're screwed anyway. ZeroNet is built on top of the Internet. If the Internet's gone, so is ZeroNet.

If you want an alternative to the Internet then you need a whole different tech stack.

**Comment by krixano** [comment]
So apparently a server can't go down unless the whole internet goes down? LOL.

**Comment by krixano** [comment]
So... First you act like an asshole to @HelloZeroNet and the ZeroNet project.. then you make ludicrous claims like every single python project that uses libraries **must** use pip. Then you repeatedly misrepresent my argument multiple times with the exact same misrepresentation that I have already said multiple times (and given evidence) that I did not say, and in fact say quite the opposite. Then you conveniently change your argument by saying you didn't say "everybody else" to mean everybody else, but rather everyone else in the Python community (even though that doesn't change my argument).

And your illogical statements that giving examples of names of people is *always* an appeal to authority - when that's actually contrary to what the definition of appeal to authority actually is - that the people must have authority and that they are given as justification *that what they believe is right* (which is *not* the same as giving them justification that not everyone believes in something - what you are trying to justify or give example to is actually important because it tells you what the person is actually... trying to prove. Are the proving that these people are right? Or are they proving that not everyone believe in a specific thing that these people do/don't believe in).

**Comment by krixano** [comment]
@BenMcLean Just wondering something. Be honest - How much of what I wrote did you just skim?
