### ISSUE TITLE
ZeroFrame API: support clearnet search engines

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1596]
- [ ] description
- [ ] keywords
- [ ] any other zite content
- [ ] videos
- [ ] news
- [ ] links
- [ ] star rating

**Comment by blurHY** [comment]
What do you mean?

**Comment by DaniellMesquita** [comment]
For sample, KopyKate creates its own dedicated clearnet proxy (kopykate.com, with only this site, users can't think they are on ZeroNet), but how the videos can be searcheable on Google?

**Comment by HelloZeroNet** [comment]
The problem is ZeroNet sites are generated on client-slide. So it won't work unless google bot visits the site, loads the inner iframe, executes the javascript, then re-parses the meta tags again after that. 

But if you search for "site:0net.io" you can see that google bot does not loads the site to inner iframe.
Also I think google does not really uses this fields for indexing as it was abused by the sites.

I think the possible solution would be to generate a search-engine friendly page on the "server side" based on dbschema.json feeds

**Comment by DaniellMesquita** [comment]
@shortcutme 

> I think the possible solution would be to generate a search-engine friendly page on the "server side" based on queries in dbschema.json "feeds" node

Good to see you know this is important.
Do you consider implementing dedicated features for proxies? (for the kopykate.com sample and others)

**Comment by DaniellMesquita** [comment]
When loading sites, append meta tags to the main page?

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
> The problem is ZeroNet sites are generated on client-slide.

Google visits the proxy zite, that haves a clearnet public URL.
All inner iframe data are put on the wrapper.html and search engines parses it

**Comment by HelloZeroNet** [comment]
The meta tags are parsed from the html source code on the GET request, so if you modify it later from javascript it will make no difference.
