### ISSUE TITLE
Optional files

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#163]
Provide a way to define not automatically downloaded files in content.json. It will make possible to create larger sites with many image (and later videos).

To do this we can simply add `optional_files` node to content.json that is identical to current `files` node. This files only downloaded if user is request it directly (by a http request).

These files are excluded from site limit calculation (10MB by default). These files lands in a cache registry which has use-configurable size, and if the cache is runs out of the configured limit the most seeded file will be automatically removed.

## Problem 1: Initial distribution
In a Multi-user imageboard site if someone uploads a new image it will not downloaded by default anyone, so he/she has to wait until someone open the site and request it.

Possible solution: It would be possible to join to a site as "sponsor" who is downloads every optional files automatically and keeps it seeding until its necessary.
Also every user would be able to add "share friend" users. If your share friend uploads a file you automatically downloads his/her files and help to distribute it.

The API also adds possibility to "pin" (where it will not removed automatically from cache) and dislike (immediately remove) files.

## Problem 2: Who has it?
Currently every peer has every file, so if you want to download a file you can request it from anyone. With optional files this is going to change: To solve this every connected peer has to keep a `hashfield` table which holds the downloaded files hashes first 4 character (only first 4 for economy reasons) eg.:
```
peer1 = ['8a42', 'fa11']
peer2 = ['12ab', 'bbc9', 'd39a']
```
If you want to download an optional file you checks if it's hash's first 4 character is in any of connected peer's hash table. If its not then you ask your connected peers to check if any of their connected peers has it. If still not found you can try to connect other peers randomly.

If you finish downloading an optional file you send the connected peers to add it to your `hashfield`, so if anyone looking for it later they will know you has it. (Probably some kind a batching is recommended)

## Current status

 - [x] Sign optional files
 - [x] Download/verify optional files
 - [x] User optional files rules (size and filename limit)
 - [x] Peer hash table sync/find peer by optional file for more efficient optional file download (who has it?)
 - [x] Super seed site (also download optional files)
 - [x] More testcase
 - [ ] ~~Modify ZeroTalk to allow file uploads~~ (did the ReactionGIFs site instead)

Later: Size limited optional cache, File pinning, User follow

**Comment by edisontrent** [comment]
I'm building an imageboard engine and it needs exactly that feature for it to be viable at all. 

The "sponsor" solution for initial distribution problem looks like a good one to me. I would like to add that it would be great to be able to not just participate as a "sponsor", but do even more work (optionally).

Example: I have a dedicated server which hosts some of my clearnet websites, and also runs some copies of ZeroNet sites of my selection. It is a powerful server and it's constantly online, however it still works as any other "regular" peer.  When new updates come in, it still transfers them just to some of close peers (5 or something like that). 

But what if I want this server to do more work? If it's a powerful machine dedicated to serving sites, I want to be able to make it more active in the net. I guess it would be good to have something like peer hierarchy so that I would mark my server as "power peer" and it would process more updates and other peers would prefer requesting that server over other "regular" peers and lower the amount of work they'd have to do. 

If this concept of peer hierarchy doesn't violate your vision of ZeroNet p2p architecture, perhaps I should submit this idea as a separate issue?

**Comment by HelloZeroNet** [comment]
Maybe a "Superseed" startup option could work where you keep more open connections and publish the new modifications more than than default 5 peer. Also currently the client decides randomly which peer he start to download the content, it could be possible to keep track the last download speed and next time he will prefer the fastest peers in the network.

I think its very easy to abuse the "seed any new site in the network" method, but this could work:
Add a "Please seed my new site" topic in ZeroTalk and create a bot that automatically starts seeding the links that sent there. This way it would be possible to have some kind a control over the sites. 
Eg. If someone sends a malicious sites there and the moderator remove the link (or it receives many down vote/report) then the bot stops seeding it.

**Comment by bashrc** [comment]
I don't think there should be a peer hierarchy, and whether or not someone has a powerful machine should be irrelevant.

**Comment by deavmi** [comment]
Yes. This is awesome, this would be a great feature.

**Comment by deavmi** [comment]
@bashrc I agree. The network must remain nuetral.

**Comment by pecc0** [comment]
"peer hierarchy" sounds like an oxymoron :)

**Comment by deavmi** [comment]
Lol yes @pecc0

**Comment by manixrock** [comment]
> holds the downloaded files hashes first 4 character (only first 4 for economy reasons)

With 4 hex characters the probabilities for collision are as follows:

Number of files | Probability of collision
--- | ---
10 | 00.068%
100 | 07.278%
1000 | 99.953%
10000 | 100.00%

Considering that a site like imgur gets about 1,500,000 images uploaded daily, the hash length should be longer than 4. Here's a graph for hash collision probability based on hash length (hex format assumed).

![has collision prob](https://cloud.githubusercontent.com/assets/785247/13554147/0adbf168-e3a9-11e5-9972-afb1a7ce42ab.png)

**Comment by HelloZeroNet** [comment]
Creating multiple sites (eg one per user) instead of increasing the hashtable length is more scalable solution.

Also a collision is not a big problem, it's just increase the network communication: the find peer by hash returning some peers that doesn't has the file you looking for.

**Comment by deavmi** [comment]
Use a on-colliding hash algo.

**Comment by HelloZeroNet** [comment]
the files are hashed using sha512, which is not-colliding (yet)

**Comment by deavmi** [comment]
by "yet" d you mean researchers have not found an example of it collidingg?

**Comment by HelloZeroNet** [comment]
yes, breaking a hash method is only matter of (cpu) time

**Comment by deavmi** [comment]
Okay. :)

**Comment by manixrock** [comment]
> Creating multiple sites (eg one per user) instead of increasing the hashtable length is more scalable solution.

Agreed.

> Also a collision is not a big problem, it's just increase the network communication: the find peer by hash returning some peers that doesn't has the file you looking for.

It would be a problem for big sites. A site with a million files using a 4-character hex hash would have to find the user with the file from 27 users, that's a lot of overhead.

I think one downside of per-follower storage (where content created by user A is only stored by the users that have accessed it) will be very prone to missing content.

A better approach might be that every user accessing a site with per-follower content, implicitly accepts to store content for ~5-10 random users (within a size limit). In exchange his own content should he make any will be stored by other users as well. This will be transient storage, and can be deleted by the system at any time to make room for newer / more popular content.

This way when someone has just posted an comment/image/video online, his content is duplicated instantly to others without waiting for them to access the content first. If he goes online immediately after posting, his content will still persist online, at least for some time.

**Comment by HelloZeroNet** [comment]
The file hashes are currently stored in a content.json file, so it would be huge with million files. (122byte/file)
It's possible to split it up using includes, but it would be still problematic. Probably building a DHT network to access static files would be better solution, but it also has drawbacks: slower and does not works well on TCP (Tor)

The goal is to stop building huge, monolith sites. Decentralized sites should be also decentralized by ownership and not only by distribution protocol.

**Comment by manixrock** [comment]
I see a few problems with the current approach.

First is a lack of immediate persistence for users that are new or without followers: right now if such a user is say on the beach, and wants to share an image of themselves and their friends then immediately shut down the laptop, it will be as if it was never uploaded. No one will be able to see it.

Another is the "15 minutes of fame" problem. Every site has a front page where they display new or trending content. What this means is that every visitor to the front page will automatically become a "follower" of the users of whatever is displayed on the front page at the time, otherwise they can't see it right? It would be awkward to ask permission for every user whose content is on the front page.

Finally it severely limits how big sites can get, and thus how many serious developers will choose the platform.

## Proposal: User Roles

Rather than limiting how big sites can get, what about allowing sites to create user roles?

For example there could be a `storage` role where the users who choose to assume the role can store (but not modify) files, a `moderator` role where they can modify other users' files, a `processing` role where processing tasks, crons can be run, etc.

For some roles only the admin can grant it (like `moderator` or `processor`), or everyone can choose it (like `storage`). For `storage` the user can choose a storage limit (like Freenet does), and for `processor` a processing power limit (like Folding@Home does). Here I discuss the `storage` role.

Say there is a site called ImgurZero with a million images (each about 1MB, totaling 1TB). Being a big site, it will have gathered a few hundred volunteer `storage` roles by now. The storage distribution method is completely up to the site developer. I'm sure libraries will spring up for all kinds of distributed storage methods. New files will be stored on the creator's host, but now the site can instantly duplicate it on hosts with `storage` roles.

The way the files are duplicated is completely up to the developer - it can be simply storing the file as is, it can be stored partially so big files are shared, it can even be stored encrypted if the file is private. If a site wants a list of all of a user's files or to read a particular file, the user doesn't have to be online, the few `storage` roles can be contacted instead. Again, it's all up to the developer, all ZeroNet has to do is provide commands to read/write to these storage locations.

From the user's point of view, he would be visiting a site where there could be a "Donate" button where he can donate some storage space and/or processing power to the site, and he gets to choose how much. The site could even prompt the user for such contributions, like Wikipedia does for money. It could look similar to requesting authentication right now.

**Comment by martinvahi** [comment]
> the files are hashed using sha512, which is not-colliding (yet)

I understand that this bug report is closed, but for future developments I mention that 
one way to alleviate the situation is to concatenate hashes of multiple hash algorithms
that are supported by "standard" tools like [rhash](https://sourceforge.net/projects/rhash/) or
[tigerdeep](https://linux.die.net/man/1/tigerdeep) or [whirlpooldeep](https://linux.die.net/man/1/whirlpooldeep). To make parsing easiery, the different hashes
can be marked with some character that is not part of the HEX digits. For example, 
Tiger hash might be marked with "t" and Whirlpool hash might be marked with "w".

    //The idea:
    s_hash="w"+whirlpool_hash(data)+"_t"+tiger_hash(data)

Relational database indexes work more efficiently, if the distribution of characters 
at the start of the strings that are stored at the indexed columns is a uniform distribution.
As the head side of the 

    s_hash="w"+whirlpool_hash(data)+"_t"+tiger_hash(data)

is very non-random, namely, it consists of "w", and the tail side of the s_hash is very random,
containing hex characters of the Tiger hash, then it makes sense to use a version of the
s_hash, where the order of s_hash characters has been reversed.

    s_hash_reversed=reverse_char_order(s_hash)  #   "abcde"  -->  "edcba"

Thank You for reading my comment :-)
