### ISSUE TITLE
Open link in new tab really doesn't works

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1736]
http://127.0.0.1:43110/fmwk.bit/
Click on header's menu, on one of the external links (blog, forum, discussion topic, contact) and it will open an empty tab.

**Comment by HelloZeroNet** [comment]
Opening new tabs from zeronet sites won't work. Always use target=_top

**Comment by DaniellMesquita** [comment]
But `target=_top` opens on the same tab

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1572

**Comment by krixano** [comment]
There's the `wrapperOpenWindow` command which opens in new tab:
https://zeronet.io/docs/site_development/zeroframe_api_reference/#wrapperopenwindow

What I do for my zites, since they are dynamic and use a js router, is route them with my router dynamically with an onclick on anchor link (making sure to put `event.preventDefault()` at the end), but also provide the herf, so that they can still middle click to open in a new tab.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1565
