### ISSUE TITLE
What is the command to recover zites privatekey from seed?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1776]

**Comment by DaniellMesquita** [comment]
> There is no ZeroFrame command for this... obviously, because then zites would be able to access your private keys. It's handled automatically in the ZeroNet client.

It is not about obvious, but CLI command to recover private key from seed and I know it exist

**Comment by krixano** [comment]
You didn't specify whether you were talking about a CLI command or a ZeroFrame command, which is the **precise** reason why people keep telling you *constantly* that you need to add more information to your issues. My assumption that you were talking about ZeroFrame happens to come from this same comment you made on an issue about *ZeroFrame commands* on the Documentation repo.

Nobody has time totry to read your fucking mind. So either be more specific, or everybody's just gonna ignore your issues because this is getting out of hand (this and your constant mistreatment of other people - which I think @HelloZeroNet should block you for, personally).

**Comment by HelloZeroNet** [comment]
Recover cloned site's private key without users.json file using only your master seed: zeronet.py `cryptGetPrivatekey 219e...061 25650465` will print the site's private key.
Where `219e...061` is your master_seed (64 char long) and `25650465` is your address_index can be found in the cloned site's content.json file.

source: http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:128

**Comment by DaniellMesquita** [comment]
@krixano
> time totry to read your fucking mind.

I'll ignore a redundant text from a real life bulled teen that is reproducing to Internet the received bullying. This is my way of creating issues (and they works), and I have proof of lots of replies that intuitively guessed what I mean, because they are humans and not a "Zuckerbot-like" like you.

@HelloZeroNet
Thanks for your kind response.

@anoadragon453 
Is that command documented?

**Comment by anoadragon453** [comment]
It is not, but then again I don't think we have documentation of the zeronet command line, which we sorely need! So noted, thanks!

**Comment by krixano** [comment]
@DaniellMesquita And there's a similar amount of proof of people asking you what you meant, which I pretty clearly already mentioned by me saying: "why people keep telling you constantly that you need to add more information to your issues".

> I have proof of lots of replies that intuitively guessed what I mean

You're so full of it. If people knew what you meant and responded then you wouldn't have made this issue. Additionally, @HelloZeroNet responded **after** you clarified that it was a CLI command.

If you post this question on a **ZeroFrame commands** issue, then people are going to assume you are talking about **ZeroFrame commands**. If you weren't talking about ZeroFrame commands, then you should have posted a *separate* issue about it with *all* of the information.
