### ISSUE TITLE
P2P Request Api

### ISSUE THREAD

**Issue by krzysztof113** [HelloZeroNet/ZeroNet#1816]
Hi

I'm creating generic site with large clustered database where each user hosts chunk of database. Search and browsing result is served by peers. Currently it's limited by antispam and sending all queries to all the peers.

Could you implement new API that would send a request to one peer that is hosting the chunk or zite? It would return payload or fallback to other peer if not responding. Peer would be for example randomly selected.

That would allow to perform searches and queries continuously with load balancing across peers.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1621

**Comment by imachug** [comment]
Sounds like a task for PeerMessage, doesn't it? @DaniellMesquita

**Comment by krzysztof113** [comment]
I don't have that plugin in any of my bundles. And it seems antispam rules would still apply if broadcasting to all.

**Comment by DaniellMesquita** [comment]
@imachug
> Sounds like a task for PeerMessage, doesn't it? @DaniellMesquita

Sounds like you're ignoring 99% of mentions/messages and replying only to 1% of random things.
Btw, PeerMessage is a base of it, but a plugin for distributed searches is needed for ZeroNet

@krzysztof113
> I don't have that plugin in any of my bundles. And it seems antispam rules would still apply if broadcasting to all.

PeerMessage doesn't handles spam as I'd heard: it is a task for the zites that uses it

**Comment by imachug** [comment]
@DaniellMesquita The fact that I reply to 1% messages just means that I fucking have no time. But you have time to make stupid statements and ask stupid questions. Though, asking stupid questions is better than not asking them at all: the fact that you say "PeerMessage doesn't handle spam" means that you didn't even want to read the manual. And there *is* a manual, and it's linked to in the readme. You said "as I heard": why not ask me and hear the opposite?

ZeroNet has great community. But a good community means that everyone listens to everyone. You don't even try to listen to others when they tell you that you're not right. Stop repeating that nofish is an asshole. You are an asshole yourself.

Krixano left ZeroNet. He was a great ZeroNet developer. Half of the sites that most people use were his sites. But he abandoned them. Guess why? Because you don't give a shit about his real life. You can't stop asking for features. You can't stop complaining that nobody implements what you want. If you continue behaving like this, nobody will ever listen to you.

---

Sorry for posting this. Someone should have said this before, but well... I am the first one to say it like this, but... believe or not, I am not the only one that doesn't like how you speak. 

---

We *do* need a CoC. Not the one Linus took, we don't need such a hugging CoC. Just make a CoC yourself.

**Comment by krzysztof113** [comment]
I won't be defending DaniellMesquita but I learned about ZN from reading issues on github and experimenting (beside docs). So spamming with questions had positive side effect. :) 
Generally it would be nice if those replies - knowledge snippets from nofish, would be put into some knowledge base.

**Comment by HelloZeroNet** [comment]
The main problem is with asking random peer with search result is you can't validate the returned values.

**Comment by krzysztof113** [comment]
I'm aware of the problem, and had some ideas how to overcome it. For example assuming the query is deterministic you can compare hashes of result from 3 peers and reject, maybe ban rogue peer.

**Comment by DaniellMesquita** [comment]
@imachug

> @DaniellMesquita The fact that I reply to 1% messages just means that I fucking have no time.

Why the need to write a bad word (f***ing)? But ok.
You don't have time (nice thing to flash/show off, so proudly), [but to ironize a issue I'd created](http://web.archive.org/web/20181211220215/https://github.com/HelloZeroNet/ZeroNet/issues/1808#issuecomment-445688669), you have time!

> But you have time to make stupid statements and ask stupid questions.

Already replied above. So contradictory from you to say it, just labeling what I say.

> Though, asking stupid questions is better than not asking them at all: the fact that you say "PeerMessage doesn't handle spam" means that you didn't even want to read the manual. And there is a manual, and it's linked to in the readme. You said "as I heard": why not ask me and hear the opposite?

YOU is who said that YOUR PLUGIN doesn't handles spam and that its up to the zite to do it. I'd preferred to believe on you, and I didn't had need to read the plugin's manual while I wasn't developing any site yet based on your plugin.

> ZeroNet has great community. But a good community means that everyone listens to everyone.

Another contradictory thing. You doesn't listen to me, and right now I said it on ZeroNet's group on Riot.im. And that's not because "I say bad things". Like ZeroMux, I say the truth here, even if I seem like a arrogant and being against strong opinions. Before you say that "what is true for one is not true for others": And the truth can't be relativized, like I can't say your documentation "[The truth about ZeroNet](https://github.com/imachug/The-Truth-about-ZeroNet)" is essentially wrong.

> You don't even try to listen to others when they tell you that you're not right.

You say it based on what?
I not only "listen", but I'm also replying, and you're not the first who I'm replying; you're just throwing a moral-english-phrased lorem ipsum to me.

> Stop repeating that nofish is an asshole. You are an asshole yourself.

Now you're going to ignorance and harassment. I'd never said bad words against Nofish. And you'd deleted your comments on IPv6 pull request where you was aggressive about Nofish. Also, did you the same about your comments in favor of Zerocoin? Its a fault on your personality.

> Krixano left ZeroNet. He was a great ZeroNet developer.

> You are an asshole yourself.

He left, but now he is on you. You never had that behavior about me, and now its you?

> Half of the sites that most people use were his sites.

No. He is not owner of ZeroPolls, Kopi, KaffieID, Kaffiene, Zirch search, ZeroVoat, ZeroMux, ZeroWiki, 0list, Nullpaste, ZeroTodos, ZeroDB, IFS, ZeroShortener, Play, ZeroLSTN, Mixtape, CodeR, 0Gallery, KopyKate.. (and most of them had disappeared) ..while Krixano created DevCenter, ZeroMedium, KxoNetwork, KxoID, KxoVid, Important Zites, ZeroExchange. You're discussing but saying that Krixano owns the majority of most used sites on ZeroNet?!

> But he abandoned them. Guess why? Because you don't give a shit about his real life.

WHAT?! He abandoned its sites because of me?
So, ZeroPolls, Kopi, Kaffiene, Zirch search, ZeroVoat, ZeroMux, ZeroWiki, Nullpaste, ZeroDB, IFS, CodeR, KopyKate were abandoned because of me?
Krixano and all other developers abandoned ZeroNet not because of me, but because of the same reason you @Imachug forfeited about improving/developing GitCenter/Kiwipedia/Your plugins/Zerocoin/Qomments.
Cowards will say that is a conspiracy theory; typical.

> You can't stop asking for features.

Not only me. If you do a user research, the majority of them agrees to having that features, to help them move from Clearnet.

> You can't stop complaining that nobody implements what you want. If you continue behaving like this, nobody will ever listen to you.

Nothing changed. There is already nobody.
And when there are no good people to be benefited, I create things just for me, because I love myself and I'm people's essential heart.
If you like to speak about nobody, then its surely because you feel yourself as nobody. Thats simple: they give order to people to not listen me, and they obey, because I'm unwanted to show good things or even make the lifes better.

> You can't stop complaining that nobody implements what you want.

The thing is not implementing what I want, but what is a need, and I envision a common sense about it.
The planet is being broken by quantum computers, mass surveillance, nanotech, artificial intelligence, hidden bombs, climate changes.. ..but the existential crisis is to don't care about the planet, earn money above of people's feelings, and being retrograde. That explains why you'd changed your behavior on ZeroNet. 

> Sorry for posting this. Someone should have said this before, but well...

Yeah, something like, by your friend Krixano (that is in favor of slavery), maybe (maybe?) from the order of the same group.

> I am the first one to say it like this, but... believe or not, I am not the only one that doesn't like how you speak.

That's normal. As "nobody" could understand Bitcoin, those persons could also say: "I am not the only one that doesn't like it".
And I'm not comparing myself with some people that also was undervalued, because you will laught, but I can't consider to debate with a user that calls me an asshole instead of saying good arguments.

**Comment by krzysztof113** [comment]
Any progress on rolling out Plugin-PeerMessage? PR sims to be stalled.

**Comment by anoadragon453** [comment]
Well I suppose since ZN is upgrading to py3 the first thing to do would be to make sure it works with the py3 branch.

**Comment by krixano** [comment]
So now you're an outright liar? Huh...

> Yeah, something like, by your friend Krixano (that is in favor of slavery)

You cannot quote *one* thing that shows I'm in favor of slavery.

> WHAT?! He abandoned its sites because of me?!

Yep... it *was* because of you. Whether or not it wasn't isn't determined by you, it's determined by me. I say it was because of you, and therefore it was. Whether you choose to believe that or not is a separate issue.

> Krixano and all other developers abandoned ZeroNet not because of me, but because of the same reason you @imachug forfeited about improving/developing GitCenter/Kiwipedia/Your plugins/Zerocoin/Qomments.
> Cowards will say that is a conspiracy theory; typical.

You have no basis whatsoever that people who say things are conspiracy theories are cowards. Perhaps... they *actually* believe it's a conspiracy theory. Apparently, according to you, a coward apparently is someone who calls someone out?

You talk conspiracy theories, are you a coward?

**Comment by krixano** [comment]
Btw, I already have a thing that can do this *without* a new plugin, only using PeerMessage (and perhaps BackgroundProcessing).

> Btw, PeerMessage is a base of it, but a plugin for distributed searches is needed for ZeroNet

**Comment by krzysztof113** [comment]
For my project PeerMesage is good enough. I just need it rolled out. 
@krixano could you point me to "thing"? It could save me part of work.
