### ISSUE TITLE
[Question] Creating a normal database on a merger-site type of site

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroNet#1886]
I have a merger-site kind of site and I would like to create a table with an index of all the merger-site compatible. I don't think it is possible to do that ? It seems to skip the json with the datas. I am right ? This is not allowed ?

I think of creating another kind of merger-site with those data. Is it the way of doing it ? It would also mean that the user have to accept it and I kind of wanted to avoid that and have the data available with the site.

Cheers,

**Comment by trenta3** [comment]
Git Center does something that solves the problem: you can create a
standard site with the merged_type of your merger-site (We will call it the
index site) and add it automatically when the user first enters your site
(ZeroNet code allows to add a site every ten seconds without asking the
user, from what I remember reading in the code). In this way you can write
and read the information you wish to the index site. The only boring thing
is that you have to hardcode its address in your code and remember to
explicitly skip it if you are considering doing some action on all the
sites with your merged_kind.

Possibly it is not allowed to store additional data in merger-site because,
being a site made to scale, one could have many possible indexing sites and
different people may be interested in different indices.
Therefore I reccomend you to follow GitCenter solution and if your site
could need different indexes, to find a way to recognize them when the user
adds one (for example by prefix or by something written in the
content.json) and save that information in the ZeroNet localstorage. This
complicates a bit the coding, but gives your users much more flexibility in
using your site (and doing it now is better than later, when you will have
to recode many parts of the site to work this way).

Il giorno sab 2 feb 2019 alle ore 21:58 Lola Dam <notifications@github.com>
ha scritto:

**Comment by rllola** [comment]
That was my guess too. I wanted to avoid creating a specific merger-site because the user has to accept it and I wanted to avoid this step. For now, I have a data.json and directly read from it for the index but it means that I am the only one who can add playlist and it is hardcoded. 

I will go with GitCenter solution, I think.

Thank you for confirming this. I am closing this issue.
