### ISSUE TITLE
Traffic obfuscation to bypass firewall

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1914]
Recently, GFW started to block peers. As Chinese developers have to bypass GFW to visit some sites, so we developed various protocols to achieve it. The protocols are strong enough to cheat GFW.
So, just integrate them into zeronet.

- [ ] Shadowsocks
- [ ] ShadowsocksR
- [ ] V2ray

@shortcutme 

DHT with traffic obfuscation is the solution

**Comment by blurHY** [comment]
I can't even publish my blog without connecting peers through proxy now.

**Comment by HelloZeroNet** [comment]
For me looks like shadowsocks is a socks5 proxy, so you should able to use it with --proxy 127.0.0.1:1080

**Comment by blurHY** [comment]
Nope. I mean each peer should use shadowsocks as reverse proxy.
Shadowsocks has two parts, client and server.

**Comment by HelloZeroNet** [comment]
> I can't even publish my blog without connecting peers through proxy now.

Are any of the trackers working for you? Do you have 1.tracker.eu.org in the tracker list? What do you see if you visit https://1.tracker.eu.org in the browser? (there should be a big welcome message) Do you have port opened?

**Comment by blurHY** [comment]
That's not about trackers.
I use proxy to connect trackers.

There're hardly any peers connected on my blog.
GFW is crazy these days, ssh connection always disconnect after 30 secs

**Comment by blurHY** [comment]
![image](https://user-images.githubusercontent.com/33171396/53330046-80916c80-3928-11e9-820f-5b3ebf31fac1.png)

![image](https://user-images.githubusercontent.com/33171396/53330083-92730f80-3928-11e9-99e9-758b3f4a5b18.png)

**Comment by blurHY** [comment]
@shortcutme ZeroNet is almost dead in Shanghai

**Comment by emacsenli** [comment]
still under 

yes ,we might need some obfs module like shadowsocks(r).

THIS IS  URGENT . ZN IS  DYING OUT of CHINA

so my idea is :
local ISPs dont have same capabilities as of GFW ,so a Chinese obfs plugin  might  work just to obfs ISPs

once Chinese obfs plugin is enabled :

1.a user specific "salt" will be required ,(a new "virgin" client will be requested his "salt" when registering)

2. a new fix  port same with p2p(mostly xunlei ,qqdownload) will be opened and listen in and out coming streams, this port is used only for peer connections and certifications (DES keys)

3. once peers got certificated ,peers will negotiate a  modern AEAD algos ,using uuid + time like v2ray to sharing website 

3.1 people can allow his ZN uuid  to be shared between peers for fast communications

3.2 


since this algo is much more complex in de/encryption, new version of pypy  should be considered(pypy and uvloop is fast as golang in async as reported )

**Comment by ValdikSS** [comment]
@HelloZeroNet this may help a bit
https://github.com/HelloZeroNet/ZeroNet/pull/1928
https://github.com/HelloZeroNet/ZeroNet/pull/1927

**Comment by ValdikSS** [comment]
@blurHY, @emacsenli, try Rev3860.

**Comment by ValdikSS** [comment]
Note that all current IP addresses of ZeroNet peers may be blocked in China, and it's better to test new obfuscation changes on new peers. For example, you can set up ZeroNet on a VPS, with bootstrap plugin, and test if it's connectable from China.

**Comment by HelloZeroNet** [comment]
According to my test it does not blocks the ips, but the ip:port combination, so changing to other port can be sufficient

**Comment by ValdikSS** [comment]
@HelloZeroNet at least two of my IP addresses no longer respond to ICMP (ping) accorting to ping.pe.

**Comment by HelloZeroNet** [comment]
I just changed my port and according to http://port.ping.pe/ it can be connected again from china regions. But it's possible that different isp/regions has different blocking

**Comment by blurHY** [comment]
> According to my test it does not blocks the ips, but the ip:port combination, so changing to other port can be sufficient

I used to setup a blog on Vultr. GFW blocked ssh connections after a few days, but port 80 remains available. That's weird

**Comment by ValdikSS** [comment]
So, did this help? Does ZeroNet work in China?

**Comment by HelloZeroNet** [comment]
My ip is still banned, so maybe the filter is not based on network traffic patterns.

**Comment by blurHY** [comment]
Chinese millions of coders use obfs tunnel to resist gfw.
