### ISSUE TITLE
upload ZeroNet gpg signing key

### ISSUE THREAD

**Issue by adrelanos** [HelloZeroNet/ZeroNet#2209]
Due to broken / unreliable gpg keyservers...

* https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f
* https://dkg.fifthhorseman.net/blog/openpgp-certificate-flooding.html

Quote:

> High-risk users should stop using the keyserver network immediately.

Could you please add ZeroNet gpg signing key to git or upload somewhere?

related:
https://github.com/HelloZeroNet/ZeroNet/issues/759

**Comment by danimesq** [comment]
Why rely on GPG/PGP if its very weak? Use Ethereum's signature or QRL.

**Comment by adrelanos** [comment]
Daniell Mesquita:
> Why rely on GPG/PGP if its very weak? Use Ethereum's signature or QRL.
> 


Or codecrypt?

But switching to a totally new signing mechanism would be a separate
ticket, I guess.

**Comment by filips123** [comment]
@DaniellMesquita Who said GPG/PGP is weak? Keyservers are unreliable, not the GPG itself.

**Adding** new signing mechanisms would be good, but **replacing** GPG would be useless.

**Comment by ghost** [comment]
I'm guessing he's talking about them being "weak" against the so-far unproven Quantum Computers that nobody has yet that we know of. Which is why he mentioned QRL - Quantum-Resistant Ledger? (just heard of this just now, lol). Not sure how we can prove things to be "Quantum-Resistant" if we don't even have quantum computers to, ya know... test on. Of course I barely understand the theory behind quantum computers let alone "quantum-resistance", so yeah...

**Comment by ghost** [comment]
> Why rely on GPG/PGP if its very weak? Use Ethereum's signature or QRL.

What the fuck are you talking about?

**Comment by adrelanos** [comment]
Looks like that happened. Now mentioned in [readme](https://github.com/HelloZeroNet/ZeroNet/blob/py3/README.md#thank-you).

> * Email: hello@zeronet.io (PGP: [960F FF2D 6C14 5AA6 13E8 491B 5B63 BAE6 CB96 13AE](https://zeronet.io/files/tamas@zeronet.io_pub.asc))

https://zeronet.io/files/tamas@zeronet.io_pub.asc

Thanks! :)

**Comment by purplesyringa** [comment]
Perhaps the issue can be closed then?
