### ISSUE TITLE
emptiness 

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2260]
emptiness

**Comment by hacktivist** [comment]
Here: https://github.com/HelloZeroNet/ZeroNet/pull/2259/commits/aaed932fb520dface3381fdda9daad79171f1e4f

**Comment by hacktivist** [comment]
You can't even think about people who has 3G or 4G in they hand. Be honest I don't think you care about anything. I seen your TED talk and you was a disaster! Failed to demonstrate in any way how your ZeroNet can be useful to fight the power! You just copied IPFS but you made some modifications. 

Do not misunderstand me! I like ZeroNet but I hate you as fuck! You are not going to be loved by anyone just because you was copied from Satoshi Nakamoto and others! You by yourself would never able to develop this. When people try to help you you keep stole code instead of having any discussion with those who propose changes. 

I think from this point on ZeroNet going to be developed by me and my friends in Switzerland and not in shitty fascist Hungary with you on the lead. You don't give a damn about people really and certainly you don't use ZeroNet in any positive or impactful way!
