### ISSUE TITLE
Namecoin Hack! ZeroNet impersonalization! 

### ISSUE THREAD

**Issue by namecoinhack** [HelloZeroNet/ZeroNet#2347]
Hello there! 

I reporting here that anyone can impersonate ZeroNet using namecoin! For example you can register **ZeroNetwork.bit**!

I hope this helps!

**Comment by namecoinhack** [comment]
@HelloZeroNet @JeremyRand

**Comment by HelloZeroNet** [comment]
you can, but only lower-cased domains accepted to the system

**Comment by namecoinhack** [comment]
Than what about this: https://0net.io/NETWORK.bit

**Comment by HelloZeroNet** [comment]
all domain requests converted to lower case before the lookup (https://github.com/HelloZeroNet/ZeroNet/blob/py3/plugins/Zeroname/SiteManagerPlugin.py#L31)

So NETWORK.bit points to network.bit

**Comment by namecoinhack** [comment]
Okay, I see so zeronet converts it to lowercase but this are still separate sites! Outside of ZeroNet it is possible to use NETWORK.bit right? What if someone removes that code you posted?

**Comment by HelloZeroNet** [comment]
"Since keys in the Namecoin key-value store are case sensitive, names MUST be in lowercase. Names with any uppercase characters SHALL be wholly ignored by compliant implementations and SHALL NOT manifest in the .bit TLD." according to the white paper

If you can edit the code, then you can point any domain to any site. You don't need to register a new domain.

**Comment by namecoinhack** [comment]
Thank you for your help and answers.

**Comment by JeremyRand** [comment]
> "Since keys in the Namecoin key-value store are case sensitive, names MUST be in lowercase. Names with any uppercase characters SHALL be wholly ignored by compliant implementations and SHALL NOT manifest in the .bit TLD." according to the white paper

Specifically, this text can be found in Namecoin's `IFA-0001.md` specification.

Of course, this could have been easily verified by, I dunno, actually trying to register such a name and seeing whether it resolved in either ZeroNet or ncdns (or just checking the spec like Tamas cites), rather than posting a trollpost like OP did.

**Comment by namecoinhack** [comment]
It is possible to register any name! Even with $ sign! :rofl:
