### ISSUE TITLE
Creating a website with zeronet.py not working on linux, the documentation here and on readthedocs are wrong

### ISSUE THREAD

**Issue by nazmifr** [HelloZeroNet/ZeroNet#2365]
Hi,

The docs says to use **zeronet.py** when, on linux at least, the ZeroNet.sh does the job while the core/zeronet.py doesn't run on it's own or with `python3 zeronet.py`. I kinda spent 10 minutes figuring out that zeronet.py was not the way.

To create a website I just had to:
`**./ZeroNet.sh siteCreate**
- Starting ZeroNet...
- Libsecpk256k1 loaded: CompiledLib in 0.070s
- Version: 0.7.1 r4206, Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0], Gevent: 1.4.0
- Generating new privatekey...
- ----------------------------------------------------------------------
- Site private key: 5KJj8dqBGkz7vpc8paerSt14LRVjEfDqsfA2zRVDU3rj6ygCRTiU
-                   !!! ^ Save it now, required to modify the site ^ !!!
- Site address:     1NiuEyRbabY1ZzjbF3UAGsFdQMXzasd6Lz
- ----------------------------------------------------------------------
? Have you secured your private key? (yes, no) > `

Here are the instances I found of where it ought to be explained:
https://zeronet.readthedocs.io/en/latest/using_zeronet/create_new_site/
https://github.com/HelloZeroNet/ZeroNet#how-can-i-create-a-zeronet-site

**Comment by decentralizedauthority** [comment]
What is your problem? I running on GNU/Linux too and I don't get it what is the problem. 

After you created the site you need to copy your stuff into `data/ 1NiuEyRbabY1ZzjbF3UAGsFdQMXzasd6Lz` and use `siteSign` afterwards. 

I would recommend to download https://github.com/HelloZeroNet/ZeroNet/archive/py3.zip extract it and than use the following command: 

`python3 zeronet.py siteCreate`

now you got an empty site under `data/yournewbitcoinaddress` you copy here everything you wish to publish and use the following command: 

`python3 zeronet.py siteSign yournewbitcoinaddress`

when you done with signing just start zeronet with `python3 zeronet.py` and you are good to go.

Don't say that is not working in GNU/Linux because that is completely false. I can confirm at least that.

**Comment by purplesyringa** [comment]
@decentralizedauthority Not all bugs can be reproduced on all machines.

**Comment by decentralizedauthority** [comment]
@imachug right, but take a deeper look at this issue. He talks about ZeroNet.sh and than about zeronet.py which is different. I think he downloaded the latest ZeroNet release from September and not https://github.com/HelloZeroNet/ZeroNet/archive/py3.zip that's why he has ZeroNet.sh and messing with the core folder. 

> doesn't run on it's own

He maybe want a system service also. Unclear actually what is his problem because no information is given about the GNU/Linux distribution he is running. Lastly while this maybe a bug, I hardly believe that is affecting everyone on GNU/Linux.

If you need a system service @nazmifr just paste here the result of this command: 
`$ uname -a`

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I have corrected the documentation:
https://github.com/HelloZeroNet/ZeroNet/commit/c08d266822d252afe2713e7f9fe281e9251f7883
https://github.com/HelloZeroNet/Documentation/commit/e986b8993d18347c41e107ca861002865ce943ab#diff-5e8b9e98f140a3c15ce84b2e7aa12469

The https://zeronet.readthedocs.io no longer gets updated, the current documentation is avaliable at https://zeronet.io/docs/using_zeronet/create_new_site/

**Comment by nazmifr** [comment]
> What is your problem? I running on GNU/Linux too and I don't get it what is the problem.
> Don't say that is not working in GNU/Linux because that is completely false. I can confirm at least that.

Hi,
Indeed I wasn't explicit enough, should have mentioned I was using this version. Anyways, that was the documentation that was the issue (in my opinion) thanks for having fixed it so that others won't have a hard time creating a site. 

And thanks for this awesome project and active community
