### ISSUE TITLE
Failed to modify max files open limit

### ISSUE THREAD

**Issue by Visentinel** [HelloZeroNet/ZeroNet#2380]
### Step 1: Please describe your environment

  * ZeroNet version: 4389
  * Operating system: Win Server 2016 Standard
  * Web browser: Any Used
  * Tor status: available
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:

Failed to modify max files open limit: [WinError 126] The specified module could not be found

#### Steps to reproduce:

  1. Run Zeronet - error is logged
  2. _____
  3. _____

#### Expected Results:

Wasn't occurring in previous version 4206

**Comment by HelloZeroNet** [comment]
It happens because of missing msvcr100.dll (can be installed by https://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe), but probably you won't reach the default (512) max opened file limit, so you can ignore it. (Probably it also happened earlier, but the startup errors was not displayed on the web interface)

Later today I will add a modification that will try to use msvcr110 and msvcr120 if msvcr100 fail to load.

**Comment by HelloZeroNet** [comment]
Fixed in Rev4394 https://github.com/HelloZeroNet/ZeroNet/commit/b6d0bf8f6b0a550d037f909b9ccf4a0e4e33da10
