### ISSUE TITLE
Deterministic Signatures in Zeronet (sslcrypto)

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2504]
@imachug's sslcrypto (https://github.com/imachug/sslcrypto) which is a zeronet lib should at least should have a good entropy (not the default)! 

The use of **Deterministic Signatures** [[RFC 6979]](https://tools.ietf.org/html/rfc6979) in ZeroNet is **highly recommended!** 

Reference to the latest merged pull request: https://github.com/HelloZeroNet/ZeroNet/pull/2503#issuecomment-606912681

**Comment by purplesyringa** [comment]
Okay, things are moving out of control so I guess it's my turn. You were referring to the `entropy=None` part, probably assuming that it means "no entropy at all". This is just a meta-value that I'm comparing `entropy` with later, in the `if not entropy:` case. I could have used `entropy="RFC6979"` as the default parameter and the checking for it with `if entropy == "RFC6979"`. I just thought `entropy=None` would be more concise, and it also doesn't let you disable entropy at all without any hacks (and perhaps you already know what you're doing at that moment).

**Comment by ghost** [comment]
@imachug I do understand that entropy=None uses default entropy **from the OS**! It is not using RFC 6979! 

I urge you to implement **Deterministic Signatures** instead and than no need to worry about or rely on entropy! @HelloZeroNet please take a look to this issue.

**Comment by filips123** [comment]
What's then [this](https://github.com/imachug/sslcrypto/blob/master/sslcrypto/_ecc.py#L472-L478)?

**Comment by ghost** [comment]
> What's then [this](https://github.com/imachug/sslcrypto/blob/master/sslcrypto/_ecc.py#L472-L478)?

**Is this you call deterministic?**

**Comment by purplesyringa** [comment]
Uh, yeah. That's *literally* the implementation of the RFC, [section 3.2](https://tools.ietf.org/html/rfc6979#section-3.2).

**Comment by ghost** [comment]
@imachug than use `entropy=entropy` instead of `entropy=None` in sslcrypto or;

try not to have this :point_down:  IF statement... sslcrypto should always use RFC

```
        data = self._digest(data, hash)
        if not entropy:
            v = b"\x01" * len(data)
            k = b"\x00" * len(data)
            k = hmac.new(k, v + b"\x00" + private_key + data, "sha256").digest()
            v = hmac.new(k, v, "sha256").digest()
            k = hmac.new(k, v + b"\x01" + private_key + data, "sha256").digest()
            v = hmac.new(k, v, "sha256").digest()
            entropy = hmac.new(k, v, "sha256").digest()
        return self._backend.sign(data, private_key, recoverable, is_compressed, entropy=entropy)
```
`if entropy != None` (I vote for this) or `if entropy is not None` :thinking: :question: 

Also, I hardly can understand why need to use both compressed and uncompressed keys.. As you see even in sslcrypto there is `is_compressed` and `is_compressed=is_compressed`.... 

Do I'm wrong? (thanks @filips123 for pointing out this part of the code)

**Comment by purplesyringa** [comment]
> than use `entropy=entropy` instead of `entropy=None` in sslcrypto

That's not so easy to do because `entropy` is not defined as a constant. Perhaps using `DETERMINISTIC_RFC6979` constant would make more sense here.

> `if entropy != None` (I vote for this) or `if entropy is not None` :thinking: :question:

I'd use `is not None` because that's the official way of comparing with `None` (do some research on why it's so if you want to).

> try not to have this :point_down: IF statement... sslcrypto should always use RFC

I've added `entropy` because someone might want to use a hardware random generator or set it themselves (think of compatibility with an existing service where another generator is used). 

> Also, I hardly can understand why need to use both compressed and uncompressed keys.. As you see even in sslcrypto there is `is_compressed` and `is_compressed=is_compressed`....

I'm not sure if you're struggling to understand the difference between `is_compressed` and `is_compressed=is_compressed`. Just to make sure: the first one is just a variable or a parameter name, the second one is a keyword argument. As for why both types are needed, that's because there are two types of Bitcoin public keys (and thus addresses): compressed and uncompressed. And if a person gives you an address, you have no way to tell whether it's compressed or not. Also, there are vanity address generators (or just generators) which can only generate nice-looking uncompressed addresses; of course, their compressed equivalents are not nice. So we have to support both types.

---

What username will you choose next?

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this issue be closed?
