### ISSUE TITLE
Tamas Kocsis is a disgusting Hungarian fascist who takes credit for GitHub pull requests

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2520]
closed

**Comment by purplesyringa** [comment]
> ZeroNet going to be rewritten

Go for it.

**Comment by ultramassiveblackhole** [comment]
> > ZeroNet going to be rewritten
> 
> Go for it.

@imachug 
I do! I also making here a public anouncement that I also replace the hashing function! SHA-512 will be replaced first with BLAKE2 and later with BLAKE3. Right now OpenSSL supports BLAKE2 and so I going to implement **https://www.openssl.org/docs/man1.1.0/man1/blake2b.html**

Again, I come up with something new and Tamas Kocsis jump on it because he is a fucking fraud shit who steals from pull requests or from comments and pretending he is the originator of the idea or the code. He has no ideas on his own. 

Here @filips123 and especially @imachug deserves credit Tamas deserves nothing, he anyway loves that Orban Viktor rules Hungary. Fucking fascist shit don't even say a thing against Orban who "Rule by Decree" (https://en.wikipedia.org/wiki/Rule_by_decree). Dictators rule by decree. 

ZeroNet was a good idea, but is never will be used by many until Tamas Kocsis rules by decree like his fu**ng fascist "prime minister". 

@imachug you will be the first to test the new software and as I said SHA-512 hashing is going to the trash and BLAKE2b will be used in that software.

**Comment by purplesyringa** [comment]
Starting an incompatible implementation would be a more complex task. Hopefully you get it finished though.

**Comment by ghost** [comment]
@imachug yes, I know but I will definitely going to implement that hashing function because it is way faster and not introduced by the National Security Agency (https://nsa.gov) [NIST]

**Comment by purplesyringa** [comment]
@HelloZeroNet Please close this orphaned issue.

**Comment by ghost** [comment]
Next time @HelloZeroNet you merge pull requests! Got it? 

@imachug @filips123  because Tamas not merged my PR look at this:
>  pip3 install -r requirements.txt
> **Ignoring gevent: markers 'python_version < "3.8"' don't match your environment**

**Comment by styromaniac** [comment]
Does anyone need to take credit? I'm just happy that ZeroNet exists and that bugs we report are fixed.

It seems like everyone who complains about Tamas Kocsis somehow cannot manage their own decentralized web project. Why? Enough of you have had gripes that you could easily form a new team.

Instead of complaining and making ad hominem attacks, at least make something that's not subject to the alleged issues. I don't know how we haven't seen a fork at the minimum yet.

My only doubt of you is having enough motivation to fork.

**Comment by ghost** [comment]
@styromaniac Tamas get money from a German company for managing github and merging commits from the public. Tamas has an easy "job", @filips123 and @imachug and other contributors get nothing for they work, so yeah I hate this guy, not just because of his TED talk... :rofl: 

So yeah, he is, what he is, takes credit for our work... :roll_eyes:

**Comment by HelloZeroNet** [comment]
Please seek for help!
