### ISSUE TITLE
not implementing (at least not here)

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2521]
#

**Comment by HellZeroNet** [comment]
@imachug @filips123 we should switch from sha512 hashing to BLAKE2, if this repository not switching I going to release my version of ZeroNet (obviously will be not called ZeroNet). Any of you want to help?

**Comment by HellZeroNet** [comment]
@HelloZeroNet you're an asshole to be honest but listen. In my opinion it would be better if sha512 hashing is dropped and replaced with BLAKE2 https://github.com/BLAKE2/BLAKE2/blob/master/b2sum/b2sum.c OpenSSL supports it and it is way faster than NSA introduced and approved (of course) SHA. 

@imachug and @filips123 can implement it way faster than me and you @HelloZeroNet also shuld help them. 

In my version only blake2b is implemented no blake2s! Is just a recommendation because truly better to hash a `BigFile` faster rather than slower.

**Comment by purplesyringa** [comment]
If you want to discuss anything with me, please open an issue on my https://github.com/imachug/ZeroNet repository and don't open them on an irrelevant project such as mainline ZeroNet client.
