### ISSUE TITLE
Sidebar file manager doesn't work if Name.YO isn't installed/enabled and if sites have a Name.YO domain in content.json

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2619]
Address bar:

>http://127.0.0.1:43110/list/syncronite.zn

The error:

>Not Found
>/media/list/syncronite.zn

**Comment by purplesyringa** [comment]
OTOH http://127.0.0.1:43110/syncronite.zn doesn't work without the plugin as well.

**Comment by styromaniac** [comment]
> OTOH http://127.0.0.1:43110/syncronite.zn doesn't work without the plugin as well.

Have you opened an issue?

I'm not sure you understand the issue here.

**Comment by purplesyringa** [comment]
Got it, you started the issue body with 'address bar' so I thought you were demanding that that URL should work. I now see that you meant that sidebar wrongly uses domain instead of address as if Name.YO was available. Sorry for confusion.

On the other hand, the same applies (or had applied before, I don't remember tbh) to ZeroHello: clicking a site with `domain` set to a Name.YO address on a node without Name.YO results in invalid URL.

**Comment by HelloZeroNet** [comment]
Thanks for reporting it should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/dcbfb8afe01da8a7d4a38ac66f7ce3e215b54777 in Rev4533 by using the same url in the browse files link as in the current url.
