### ISSUE TITLE
zero:// urls scheme

### ISSUE THREAD

**Issue by GomZik** [HelloZeroNet/ZeroNet#266]
What do you think about handeling urls like
zero://<hash or domain>
and automatically open new tab in browser?

**Comment by HelloZeroNet** [comment]
The browsers does not allows this. Related topic: https://github.com/HelloZeroNet/ZeroNet/issues/83

**Comment by GomZik** [comment]
But, you can handle urls like zero://<hash> by zeronet core (or something like) and open in browser with url http://127.0.0.1/<hash>

**Comment by iShift** [comment]
use case is - make link zeronet://hash and post it in normal internet that if you click it (and you have zeronet) zeronet register it as protocol for this links and convert link that open (like it does after start in new browser window) 

I think that it better than nothing

**Comment by HelloZeroNet** [comment]
Using the [Chrome plugin](https://chrome.google.com/webstore/detail/zeronet-protocol/cpkpdcdljfbnepgfejplkhdnopniieop) you can access sites using http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D and http://zeroid.bit

I think it's better, because no need to modify OS settings (cross-platform issues) and for example in chrome you get confirmation window if you want to click on external protocol handler's link (eg. torrent://)

**Comment by iShift** [comment]
but user should install +1 new software, if you prefer chrome plugin as long wrapper you should give link to it in zero hello

**Comment by dmp1ce** [comment]
I think an Electron app could implement a custom browser for zero:// URLs.

**Comment by OliverCole** [comment]
@dmp1ce Check out [Beaker](https://github.com/beakerbrowser/beaker) and the relevant [ZeroNet ticket](https://github.com/HelloZeroNet/ZeroNet/issues/530).

**Comment by filips123** [comment]
There are a few related issues about URL scheme and handler (#83, #266, #1295). I posted my idea about this in https://github.com/HelloZeroNet/ZeroNet/issues/83#issuecomment-489426817.
