### ISSUE TITLE
CryptoMessage error on start

### ISSUE THREAD

**Issue by Stivencannor** [HelloZeroNet/ZeroNet#2671]
### hello, i have an error after updating to new version (rev4548). I'm using termux and rev4540 has not this problem.

  * ZeroNet version: 0.7.2  rev 4548
  * Operating system: android termux
  * Web browser: chrome
  * Tor status: always
  * Special configuration: message encryption, external tor running

I have this error (at picture):
It say zeronet is running but i know its not. And i closed them by pkill. I restarted phone. And i got this error at first run after fetching/pull github repo.

![Screenshot_20201103-105812_Termux](https://user-images.githubusercontent.com/31382284/97959614-fb30b180-1dc4-11eb-8ca0-83034d9bc9aa.jpg)

#### Expected Results:
I can start zeronet rev4540 correctly by described config.
Rev4540 is running fast but i got this error after long time "Starting ZeroNet" message.

**Comment by rex4539** [comment]
I see the same bug here on macOS. Probably related to https://github.com/HelloZeroNet/ZeroNet/issues/2672.

**Comment by JabbaDesilijicTiure** [comment]
@Stivencannor disable the cryptmessage plugin that is one option for now.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed in Rev4549 https://github.com/HelloZeroNet/ZeroNet/commit/57dda4e6d6c20bd795ecaa18902289d516a87c6d

To fix it manually you have to replace the file src/util/OpensslFindPatch.py with https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/src/util/OpensslFindPatch.py
