### ISSUE TITLE
On windows start self tor process, but don't use already started

### ISSUE THREAD

**Issue by wrewolf** [HelloZeroNet/ZeroNet#276]

**Comment by wrewolf** [comment]
May be need try check tor service port before start self tor process?

**Comment by HelloZeroNet** [comment]
If you start your tor process on port 9050 and 9051, then it should work fine. The tor browser uses different port (9150 and 9151), be we don't connect to that service, because if you close the tor browser it would also make zeronet stop working.

If you want to share service with the browser then you have to start it using `zeronet.py --tor_controller 127.0.0.1:9151 --tor_proxy 127.0.0.1:9150`

**Comment by border0464111** [comment]
Does it solved your issue @wrewolf ?

**Comment by imachug** [comment]
@HelloZeroNet This issue is outdated and has been resolved -- can we close it?
