### ISSUE TITLE
FIXED:

### ISSUE THREAD

**Issue by krushnadeore** [HelloZeroNet/ZeroNet#2792]
repo owner can freely delete this issue ...

**Comment by caryoscelus** [comment]
please note that ZeroNet is no longer maintained . there are a couple active forks available . as a maintainer of [zeronet-conservancy](https://github.com/zeronet-conservancy/zeronet-conservancy/) i'm inviting you to give it a try , though at the moment only source-based installation is supported . there are no instructions for mac os x yet , but since it's unix-based os , you need to install python3-venv and python3-pip and the rest of instructions are the same as for gnu/linux
