### ISSUE TITLE
I'm ready to continue developing zeronet

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2799]
I am ready to completely restore and improve zeronet if there are investors.
I fully understand all the shortcomings of this project and know what can be done to get around them.

If anyone is willing to invest, please contact me.

**Comment by ple1n** [comment]
I don't have money to invest, but I myself have been focusing on dweb for some time. If I had time I would fork this project too, but I'm a student. I wonder what your plans are. 

Edit: Better write a new one instead

**Comment by CalunVier** [comment]
@

> I don't have money to invest, but I myself have been focusing on dweb for some time. If I had time I would fork this project too, but I'm a student. I wonder what your plans are.

Is your project still in development? I see your home page has a dweb project, but the last commit was two years ago

**Comment by purplesyringa** [comment]
@canewsin is working on the project [here](https://github.com/ZeroNetX/), if anyone else wants to help, you'd better join them.

**Comment by ple1n** [comment]
@CalunVier I was busy with study, and designing the architecture requires a large block of time which I didn't have. I'm not quite experienced, and I changed my mind a few times during development. There isn't a clear or an optimal solution.

I thought about the development of Melotte again. The problem is, most of Melotte's goals are already on IPFS's roadmap, which means Melotte only needs a little code, and currently it's not a good idea to do anything because the codebase is not stable. Many features of Melotte require forking IPFS, and that messes things up. I stopped developing it hence. For example, there are proposals for F2F, and WoT, and permission stuff. They don't plan to build a docker-like thing (part of Melotte) though. That's actually understandable, since browsers are already a kind of container. With some changes it could implement the features of Melotte.  

Currently, in terms of protocol development, I think it's better to write proposals rather than write code https://github.com/ipfs/roadmap/issues

As their roadmap implies, it would be only a few lines away from implementing ZeroTalk after the protocol got written. They are in favor of a slower development however

**Comment by mx5kevin** [comment]
The software industry is full of talentless  contar-programmers who sitting unusable, rough programs which will never work.  They promise big ones, big marketing, there are but they are really useless. If that team does a bad job, even there will be no results in years to come. We are full of promises and systems that fail to do his job. This is exactly a project that requires several independent teams. Investing makes sense if the programmer does what I pay for. This requires results, what kind of work the team does.

**Comment by mx5kevin** [comment]
The original developer was well paid in bitcoin. In 5 years was unable to create such a system where file sharing works. Large files are inaccessible and inoperable. All engineering failure. The download/seeding system is almost unusable. The basic concept itself is inoperable for files to spread quickly on the network. The concept is simple the full content need to be downloaded at one click, seeded at system startup. From A point to B need to transfer the full content to C get the full content. Who actively runs large websites on the network, and sharing large files, see the system through the eyes of a website owner (with, PC, Laptop, Mobile and not the 24/7 online server conception, and not the paid hosting conception) we need such a development teams. A lot of people, programmers go against the interests of users. Several different independent development teams are needed here. If someone doesn’t want to, they don’t know, they have ulterior motives, there should always be a different development team.
