### ISSUE TITLE
It's a good project; PLEASE keep it UP TO DATE!

### ISSUE THREAD

**Issue by AhmadrezaAlipouryaan** [HelloZeroNet/ZeroNet#2808]
Some people need to use this type of applications.
Last update is 2019
Please keep it up to date.
Thanks!

**Comment by caryoscelus** [comment]
we're developing a fork/continuation at https://github.com/zeronet-conservancy/zeronet-conservancy . there are more forks , more or less active , too

thanks for your interest!

**Comment by AhmadrezaAlipouryaan** [comment]
> we're developing a fork/continuation at https://github.com/zeronet-conservancy/zeronet-conservancy . there are more forks , more or less active , too
> 
> thanks for your interest!

Thanks🙏

**Comment by mx5kevin** [comment]
**The original developer does not deal with the project. He just disappeared.** Others who took over the project they promises big false things but they do nothing. Plans are promised that will not work before implementation already in the design. They are waiting for donations for work that is made of someone else. Or they want to steal from users. Then there are a lot of people who came from scam projects to advertise his own crap for the decentralized community (like the crypto scams with his self made manipulated currency teams). Which (the cryptocurrency team) is an open theft of users and investors money. The original developer left behind a project for which to download system, sharing system are full of bugs and in vain seeding somebody the files another users can not download it. And this problem is something no one has fixed from about 5 years. Everyone can watch torrent networks, and clients, the torrent protocol are working the files are available after 10 years later in torrent networks without any central server. That it's not available here not that the case the users not seeding the content. With which developers excuse themselves.  Instead of fixing the problem they recommend a paid system wit a centralized server setup with a SCAM COIN IPFS/Filecoin. And another developer are promising blockchain storage system which is out of the question to possible build on by own self make a working setup. Such a job requires a big team and need to integrate their work in ZeroNet project what not are the case.

**Comment by caryoscelus** [comment]
@mx5kevin please list all the names and the links , otherwise your statement is a big FUD mixed with bits of truth (as any good propaganda does) . there are many problems with the project , original version and otherwise , but they have to be dealt with separately rather than lumping them together scaring people of

**Comment by mx5kevin** [comment]
> @mx5kevin please list all the names and the links , otherwise your statement is a big FUD mixed with bits of truth (as any good propaganda does) . there are many problems with the project , original version and otherwise , but they have to be dealt with separately rather than lumping them together scaring people of

Just go to ZeroTalk. On ZeroNetX project (issues) the first topic (You should get zeronet to support Monroe coins), the 4. topic (UDP DHT + Tor level anonymity) buy some Lokinet coin. ZeroTalk full of Filecoin, IPFS, odysee and other propaganda. But caryoscelus it's not your project either the original developper have Linux, Windows, someone make Android version, links in download page, but you will give only a nice donation link, so you're not doing anything. **You copied the original developer project, you made minor changes to it, promote your setup in the original team dead (issue site), and wait the donations here in this topic! And try redirect the users to your copied project!**

**Comment by caryoscelus** [comment]
@mx5kevin 

> the original developper have Linux, Windows [binaries]

security holes . we're explicitly against producing binaries until there's infrastructure of making them reproducible (can you help with that? would be highly appreciated)

> made minor changes to it

the diffs are open to the public . even our dev branches are open to the public

> wait the donations here in this topic!

lol really

> ZeroTalk full of Filecoin, IPFS, odysee and other propaganda

that's free speech for you . just mute the users whom you consider spammers

> And try redirect the users to your copied project!

what , do you want me to redirect them to an abandoned fork that i haven't audited or to ZNX ? or to say "the project is dead, enjoy your government censorship" ? do you not realize that copying isn't a bad word and that's how free software develops when original authors abandon the project

> original team

do your research , please . there was never a team and that's why we're here

please kindly redirect your energy into making your fork that will not ask for money and will support users and will fix broken things and will be prepared to face the future challenges



ps: it's nice to feel so important other people want to shout at you , but this is probably the last response from me you're getting [unless you do something constructive] . have a good day

**Comment by mx5kevin** [comment]
**caryoscelus you want money with a work that not yours, and nothing behind it from your work, and no progress. You would silence users (bad starting point, and base for a decentralized, censor free software developer). And you're not even aware of what's going on this network.** Your project is useless, who wants to install it to Windows, Android, Linux, Mac, they cant. You don't even have an official site in the internet! 😄 According to your own confession the code you use is not from the original, or 100% trusted source, and You said just trust that it is not include a virus or backdoor inside (because someone has already modified it before you).  The project currently are in some wrong hands. There are many people who do not want to take the project in the right direction for the community.

The are another ZeroNetX project with downloadable binaries:

https://github.com/ZeroNetX/ZeroNet

ZeroNetX official site:

https://zeronet.dev/

Opened its own forum on ZeroNet for users feedback, have all binaries Windows, Mac, Linux, Android to download. He don't want to silence users (as you want now), have a blog with plans, communicates with the users, running a clearnet proxy. He still has few users on the ZeroHello page. This is currently the only one biggest ZeroNet project what currently working. This is how a good debut begins! If the project long term goes dead then the community is not worthy of such a network.

**Comment by ghost** [comment]
@AhmadrezaAlipouryaan do not use the version that sent to you by @caryoscelus, she is a scammer who trolling every single repository and trying to collect money. Listen to @mx5kevin.

Read also this: https://github.com/HelloZeroNet/ZeroNet/issues/2807

**Comment by ghost** [comment]
@imachug is a troll too who now pretending that he "stands with Richard M. Stallman" while he @imachug openly attacked me and others who proposed the GNU GPLv3 license (that written by Stallman) for ZeroNet.

**Comment by purplesyringa** [comment]
Kindly go fuck yourself.

Yours truly,

**Comment by peertopeernetworkdeveloper** [comment]
Here is the Ukrainian neo-nazi @imachug again, aren't you banging your Azov Batallion buddies in Ukraine in the ass?

**Comment by peertopeernetworkdeveloper** [comment]
Stop trolling the ZeroNet repository before I make a personal website with your name and expose how you trolled the Free Software Foundation too.

**Comment by AhmadrezaAlipouryaan** [comment]
Still no updates ::::(

**Comment by caryoscelus** [comment]
@AhmadrezaAlipouryaan zeronet-conservancy is still alive . original project is unfortunately dead
