### ISSUE TITLE
ZeroNet AppImage

### ISSUE THREAD

**Issue by kskarthik** [HelloZeroNet/ZeroNet#283]
[Appimage](http://appimage.org) helps packing apps which can run on all major Linux distribution s based on concept of _one app = one file_

If zeronet can be packed along with all its dependencies inside an appimage, users can simply download give permission & run the file. 

Popular apps like scribus, krita are also adopting this method to distribute their apps. 

Projects repo: https://github.com/probonopd/AppImagekit 

The developer @probonopd is happy to help you packing your app :)

**Comment by HelloZeroNet** [comment]
Yeah, it would be nice, last night i started having openssl segfaults on CenOS. Only compiling python 2.7.11 and the latest openssl solved it. (CentOS have crippled openssl by default that does not support bitcoin's curve)

My concerns:
 - It would broke the semiauto-update (you can update to the latest source code with one click)
 - Plugins (separate .py files)

For windows we have a ZeroBundle package that has python + all dependencies packed, but leave the source code on the hdd as it is. Would this possible with AppImagekit?

A similar solution for mac also would be nice, but I have OSX no access.

**Comment by ashleypt** [comment]
Maybe plugins should use a folder in "My Documents" or $HOME, loading them dynamically. As for semiauto-update, why can't it download the latest AppImage rather than source if you're using the AppImage version?

that being said, I'm not sure I like this way of packaging things for Linux... how do you keep all the component packages of the AppImage up to date?

**Comment by kskarthik** [comment]
I think you are talking about atomic updates. Yes. It can be possible to update specific parts of the app. Just have a look into that project once you find some time :) Also it's a simple process to turn an app into app image. No special skills required.

**Comment by probonopd** [comment]
Whenever there is an update, then there should be a new version of the AppImage, as AppImages are immutable (which I consider a feature). There is a mechanism for updating AppImages using binary delta updates, which means that only the portions of the AppImage are re-downloaded that have been changed since the last version (e.g., if the Python runtime did not change, then these bytes do not have to be re-downloaded). 

https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md

**Comment by kskarthik** [comment]
@HelloZeroNet since you are now providing a static archive for linux, why don't you distribute as appimage ? I tried making it but faced path relocation problems. I'm not good at fixing those. @probonopd help needed in this case...

**Comment by HelloZeroNet** [comment]
it could be possible, but not sure about the advantage

**Comment by kskarthik** [comment]
@HelloZeroNet  please give a try. regarding advantages, all files are in compressed state all the time & makes the app more portable

**Comment by probonopd** [comment]
@kskarthik please reopen, I'd like to give this a try :-)

**Comment by border0464111** [comment]
It's more an issue of https://github.com/HelloZeroNet/ZeroBundle as this repo hold strickly the core.

**Comment by probonopd** [comment]
Thanks @border0464111, opened https://github.com/HelloZeroNet/ZeroBundle/issues/17
