### ISSUE TITLE
Localization i18n

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#322]
What you think about localization for sites in zero network ? 
we can use https://github.com/fnando/i18n-js or https://github.com/i18next/i18next for that

**Comment by HelloZeroNet** [comment]
https://github.com/HelloZeroNet/ZeroTalk/pull/12

**Comment by HelloZeroNet** [comment]
## Idea1: Hotpatch

You would be able to "hotpatch" any of the site's files based on language files, eg. if you have a `translate/ru.json` containing:

```
{
 "js/all.js": {
   "Please, your choose account before upvoting.": "Russian translation"
  }
}
```

And the user have selected Russian as language, then ZeroNet will return all.js replaced "Please, your choose account before upvoting." with "Russian translation". To avoid partial matching the part should start and end with characters: `' " < >`

If required (will try to translate zerohello and zerotalk and it will turns out), then we could add allow partial and regex matches by `js/all.js:re` and `js/all.js:partial`

- [ ] Performance benchmarks
- [ ] Implement as "Multilanguage" plugin
- [ ] ZeroHello modification to allow select preffered laguage

**Comment by HelloZeroNet** [comment]
First benchmarks: https://gist.github.com/HelloZeroNet/f684d2f1eb7807a124b3 from my old core2duo cpu:

- it takes 4.8ms to replace the texts in zerotalk's all.js (220kb) 
- down to 2.6ms if we skip js/lib/* from translating
- 2x more translate replacements adds on +20% running time

So probably we don't need to cache translated files.

**Comment by HelloZeroNet** [comment]
Added in 0.5.1, translation files:
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Translate/languages/hu.json
https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/Sidebar/languages/hu.json
https://github.com/HelloZeroNet/ZeroHello/blob/master/languages/hu.json
https://github.com/HelloZeroNet/ZeroMe/blob/master/languages/hu.json
https://github.com/HelloZeroNet/ZeroTalk/blob/master/languages/hu.json

**Comment by filips123** [comment]
@HelloZeroNet Do you have any localisation platform for ZeroNet?
