### ISSUE TITLE
fix hash forwarding

### ISSUE THREAD

**Issue by basxto** [HelloZeroNet/ZeroNet#375]
As far as I can see hashes get only forwarded (from wrapper to actual zite) when they change.

Adding the code from window.onhashchange to onLoad in Wrapper.coffee might do the job.

This might be handy for keys which should not be transferred to the server. It does not really matter for a local node, but for a proxy, you don't own, it would.

**Comment by HelloZeroNet** [comment]
The problem is the wrapper does not know if the frame loaded or not. You have to send a "innerLoaded" command to the wrapper when you finished rendering your page (loaded all database query) and it will add the hash to the site url. https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/media/Wrapper.coffee#L100

**Comment by basxto** [comment]
Okay, thanks, got it working this way
