### ISSUE TITLE
Can change site BTC address via HelloZeroNet pannel

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#549]

**Comment by obv-mikhail** [comment]
Clone the site, and delete the old one.

From what I understand, it is impossible to change the address of an existing site because it will still exist if other people are seeding it. Even if you delete all content and republish the site, it will still be seeded by other people. Correct me if I am wrong.

**Comment by DaniellMesquito** [comment]
I don't have what correct in your comment, but what suggest. The address can be changed, yes. But clone the site and delete the old one is a solution. But provide it in option for end user will be good.

**Comment by HelloZeroNet** [comment]
It's not possible to change the site's address

**Comment by beenotung** [comment]
I understand a site cannot be renamed or deleted directly.
But we can effective 'rename' a site using the following steps:
1. create a new site
2. copy the content from old site to new site
3. fix the links in the new site
4. publish the new site
5. replace the index.html of the old site to redirect to the new site

The tricky part is to configure the content.json correctly for the new site.
For example the `signer_sign` and `signs` in the content.json. Otherwise you will not be able to publish the new site.
