### ISSUE TITLE
error by fileWrite on MergerSites (Internal error: TypeError: string indices must be integers, not tuple)

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#579]
after changing my sites to use mergerSites, im not longer able to save an image via Page.cmd('fileWrite'). 
here is the function:

			    var path = 'uploads/images/' + $scope.channel.img;
			    var canvas =  document.getElementById('canvas');
			    var previewImgUrl = $scope.imgSrc.split(',')[1];
				Page.cmd("fileWrite",[path, previewImgUrl], function(res) {
					if (res === 'ok'){
						$scope.updateChannel();
					}
				});

and the error im getting:
TypeError: string indices must be integers, not tuple in UiWebsocket.py line 99 > UiWebsocket.py line 178 > MergerSitePlugin.py line 127 > MergerSitePlugin.py line 121 > UiWebsocket.py line 402

this worked perfectly before the mergerSites update now im getting this error constantly. help!

**Comment by HelloZeroNet** [comment]
It's fixed in latest Revision: 60dd797d1a99605099885de5b9a7f050cd16a312

It happens when the file you want to write is in "bad_files". It means the file has been referenced/tried to download before, but it was failed. (You can check bad files in the sidebar)

To ignore this dialog you can use `Page.cmd("fileWrite",{"inner_path": path, "content_base64": previewImgUrl, "ignore_bad_files": true}...`
