### ISSUE TITLE
Please i need help

### ISSUE THREAD

**Issue by Osvalcosta** [HelloZeroNet/ZeroNet#629]
I am running ZeroNet on my localhost using ubuntu and i want my site from another computer which is not running ZeroNet..................

Ex: Computher 1 running ZeroNet on port 43110
      Computer 2 accessing ZeroNet site from computer one on port 8080 " something like that"

**Comment by HelloZeroNet** [comment]
You need to start it using `zeronet.py --ui_ip "*"` then the remote machine will able to reach it using http://yourip:43110 (you can add --ui_port 8080 if you want that port instead of 43110)

More info:
http://zeronet.readthedocs.io/en/latest/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine
