### ISSUE TITLE
decentralized blockchain explorer

### ISSUE THREAD

**Issue by migrantdeduct80** [HelloZeroNet/ZeroNet#75]
I am asking for ZeroNet to have a bitcoin Blockchain explorer that is able to run on multiple computers or phones sending and receiving say a that is always online and is not able to be shutdown by using its own bitcoin software and nodes it checks with and uses nodes that are posted and tested on something like 

"""Bitnodes is currently being developed to estimate the size of the Bitcoin network by finding all the reachable nodes in the network."""

But this can be on ZeroNet instead of using TLDS and a centralized dns.

This can be expanded for reachable nodes but eventually it acts like a site similar to blockchain.info but with a ZeroNet address instead with a wallet service would be far superior than blockchain.info

Thanks and looking forward to development of this website including wallet that is using peers as hosts instead of a cloud or datacenter!

**Comment by migrantdeduct80** [comment]
Update is you can use name coin and. Bit addresses so the Decentralized Blockchain can be a. Bit address

**Comment by HelloZeroNet** [comment]
The problem is to do this we have to store the blockchain on every machine and it would require around 50gb of database on every machine that updated every second.

It could be possible by running a full bitcoin node on every machine and zeronet only distribute the html/javascript/css that required to query the bitcoind.
