### ISSUE TITLE
site creation within zero doesnt work

### ISSUE THREAD

**Issue by JazzMaster** [HelloZeroNet/ZeroNet#804]
If you try (within zero) to make a site, you can never sign it. The private key never shows up. This only works via the console. signing existing and publishing an existing zite is ok(but a moot point if you interrupt the console-sign and publish- and then reconnect)

A solution could use dynamic JS to display the private key. And those pop ups dont stay up long enough to read. Double the delay?

**Comment by MuxZeroNet** [comment]
Hello, newcomer! ZeroNet has a very interesting sidebar. You can see a `0` button at the top right corner of your homepage. Instead of clicking on it, you drag it to the left. The sidebar will show up. You can sign your site there.

Your private key is saved in `users.json`. ZeroNet does not prompt you to type in your private key if it is saved in that file.

**Comment by grez911** [comment]
@HelloZeroNet Please, close.
