### ISSUE TITLE
wrapperReplaceState hash

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#918]
Is it possible to make `wrapperReplaceState` change only hash and not reload the entire page?
Example:
```javascript
page.cmd("wrapperReplaceState", [null, "", "#abc"]);
```
This command changes URL to `http://127.0.0.1:43110/.../?#abc`. Notice that `?`. That's why the page reloads. I want to get `http://127.0.0.1:43110/.../#abc`.

**Comment by imachug** [comment]
Running:
```javascript
window.location.href = "#abc";
```
just shows `Wrapper nonce error`.

**Comment by HelloZeroNet** [comment]
Fixed in https://github.com/HelloZeroNet/ZeroNet/commit/34a6337c014f747fc28ea3022e1754fce852a277
If the url starts with `#` it won't add `?` anymore, but I recommend you to use `?` instead of `#` (eg. `page.cmd("wrapperReplaceState", [null, "", "?abc"]);`) as hashtags are originally for jumping to anchors on one page and using replace/pushState should not reload the page.
