### ISSUE TITLE
Is this a bug ? All users can send files to any mutil-user zites.

### ISSUE THREAD

**Issue by funny110** [HelloZeroNet/ZeroNet#943]
Users just set an optional tag to himself  folder's content.json and they can send all type of files to zites. Is this a bug of zeronet ? If this is not a bug, please close :)

**Comment by l5h5t7** [comment]
I don't think so. But too big optional files will take up too much memory usage, then ZeroNet will be killed. (#903)

**Comment by funny110** [comment]
@l5h5t7 By the way, please repo ZeroTalk's zerotalk's Chinese translation to Nofish.
Translate `主论坛` and `主論壇` to `English`, These day a lot of Chinese talk on ZeroTalk.

**Comment by HelloZeroNet** [comment]
It's intentional, I don't see any problems with it, but you can disable it by adding `"max_size_optional": 0` to permission_rules / ".*" in `data/users/content.json`

I have changed 主論壇 and 主论坛 to English, but I don't think it's going to change anything since there is already a "Please use English, you can reach other language forums at the top of this page" warning at new topic creation.

@l5h5t7: I have added  --file_size_limit option in latest revision.
