### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/ZeroNet#989]
[ReDoS](https://en.wikipedia.org/wiki/ReDoS) turns out to be an old and classical attack. A program is vulnerable to this attack if regular expressions are controlled by user input. There are a few possible solutions:

- Use a linear complexity [RegEx library](https://github.com/facebook/pyre2/).
- [Timeout](https://stackoverflow.com/questions/11901328/how-to-timeout-function-in-python-timeout-less-than-a-second) a RegEx function call.
- Deprecate regular expressions. Use a shell-like matching syntax `["updater/*", "*.mp4", "optional_*"]`.

**Comment by HelloZeroNet** [comment]
None if these are easy solutions:
 - Pyre: Binary module
 - Timeout: It's only working under Unix
 - Shell-like syntax: Basically breaking all current sites.

So I think Timeout is the only possible solution, but in that case probably we need to run the regex code in separate thread or process.

**Comment by HelloZeroNet** [comment]
Unfortunately looks like python can't interrupt re.match running in separate thread:
```python
import sys, re
import threading
import time
import thread
import gevent
import gevent.monkey

gevent.monkey.patch_all(thread=False)


# via https://gist.github.com/aaronchall/6331661fe0185c30a0b4
def quit_function(fn_name):
    thread.interrupt_main()

def exit_after(s):
    def outer(fn):
        def inner(*args, **kwargs):
            timer = threading.Timer(s, quit_function, args=[fn.__name__])
            timer.start()
            try:
                result = fn(*args, **kwargs)
            finally:
                timer.cancel()
            return result
        return inner
    return outer



@exit_after(0.01)
def whileTimeout():
    i = 0
    while 1:
        i += 1
s = time.time()
try:
    whileTimeout()
except KeyboardInterrupt, err:
    print "KeyboardInterrupt"
print "whileTimeout", time.time() -s


@exit_after(0.01)
def matchTimeout(pattern, s):
    return re.match(pattern, s)

s = time.time()
matchTimeout("^A(B|C+)+D$", "ACCCCCCCCCCCCCCCCCCCCCCCCX")
print "matchTimeout", time.time() -s
```

```
KeyboardInterrupt
whileTimeout 0.010999917984
matchTimeout 1.40499997139
```

**Comment by HelloZeroNet** [comment]
At this point the the simplest solution that comes to my mind that does not have any backward compatibility issue is sanitize the patterns: only allow repetition of any character, so enforcing the `.` before the characters `*`, `+`, `{`. 
I think this should not affect any current use cases and would protect from evil patterns. (maybe we should also limit the patterns to 255 char)

Affected parts:
 - dbschema.json: matching maps to load to sqlite database. Executed after every downloaded file, so performance on this is critical
 - content.json: ignore, optional patterns. Less critical, because it's only executed on signing

**Comment by HelloZeroNet** [comment]
Added in rev2153
